### ISSUE TITLE
SuggestedAction support in Skype channel

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/botbuilder-dotnet#1030]
## Version
Microsoft.Bot.Builder 4.0.7
Bot Framework Emulator (V4 PREVIEW) version: 4.0.0-preview.40025

## Describe the bug
SuggestedAction is not supported in Skype (Windows, app. v. 14.32.55.0)

## To Reproduce
Send a message activity containing a SuggestedAction
```cs
await context.SendActivityAsync(MessageFactory.SuggestedActions(new CardAction[] { new CardAction(type: ActionTypes.PostBack, title: "Test it", text: "Test it", value: "Show me the shop catalog") }));
```

When executing last statement, I always get an exception `Operation returned an invalid status code 'BadRequest'`
```
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\Conversations.cs:line 1121
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 241
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 298
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 196
   at Microsoft.eShopOnContainers.Bot.API.Dialogs.Help.HelpDialog.ProcessHelpChoices(WaterfallStepContext dc, CancellationToken cancellationToken) in C:\Users\frank\Work\eShoConAI\src\Bots\Bot.Core.API\Dialogs\Help\HelpDialog.cs:line 54
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\WaterfallDialog.cs:line 108
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\WaterfallDialog.cs:line 130
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\WaterfallDialog.cs:line 103
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 169
   at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\Prompts\Prompt.cs:line 98
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 130
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 65
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 130
   at Microsoft.eShopOnContainers.Bot.API.Dialogs.Main.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\Users\frank\Work\eShoConAI\src\Bots\Bot.Core.API\Dialogs\Main\RouterDialog.cs:line 34
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 65
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 130
   at Microsoft.eShopOnContainers.Bot.API.eShopBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\frank\Work\eShoConAI\src\Bots\Bot.Core.API\eShopBot.cs:line 69
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 60
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167
```

Same code works in emulator. I also tested with other ActionTypes (`ActionTypes.ImBack` and `ActionTypes.PostBack`). I also tested other cases, for instance, a suggested action containing many CardAction, and it also fails.

## Expected behavior
SuggestedAction/CardAction works in Skype channel

[bug]

**Comment by franperezlopez** [comment]
Sorry to bother again ... but your affirmation is not totally correct

Adding the following line:
```cs
await context.SendActivityAsync(MessageFactory.SuggestedActions(new CardAction[] { new CardAction(type: ActionTypes.PostBack, title: "Test it", text: "Test it", value: "Show me the shop catalog") }, text: "I don't need this prompt"));
```

I've got the following output in skype:
![image](https://user-images.githubusercontent.com/1222398/47118765-aa46d280-d268-11e8-91f5-20885b24bb8a.png)

which is not what I want, because I don't need the extra prompt. Besides, without the `text` parameter, works flawlessly in the emulator.

But one thing is correct: adding the text parameter, the click is handled correctly and I don't get any exception. But the behaviour is very different between the emulator and Skype app

**Comment by JasonSowers** [comment]
All channels have their own behavior as the rest API for each channel is not exactly the same.  The emulator is not a good baseline for channel behavior.  For example, some channels do not even render suggested actions like slack.  Skype requires text or an attachment to be included with the activity or you will get the error you were seeing.   To debug locally in a channel see [this blog](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/).  If you are targeting a specific channel this is how you should do you debugging while developing because as I mentioned before the emulator is not the same as every channel.
