### ISSUE TITLE
ConnectorClient builds illegal ProductInfo header string resulting in TypeInitializationException on MacOSX

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1408]
## Version
v4.2.x

## Describe the bug
A developer was building a bot leveraging .NET Core on MacOSX. This was working great and then suddenly this exception started being thrown which blocked them from running the bot locally from that point forward:

```
An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase' threw an exception. ---> System.FormatException: The format of value 'Darwin18.2.0DarwinKernelVersion18.2.0ThuDec20204653PST2018rootxnu-4903.241.11/RELEASE_X86_64' is invalid.
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.ProductHeaderValue..ctor(String name, String version)
   at Microsoft.Rest.ServiceClient`1.UpdateDefaultUserAgentList(String headerName, String headerValue)
   at Microsoft.Rest.ServiceClient`1.get_DefaultUserAgentInfoList()
   at Microsoft.Rest.ServiceClient`1.InitializeHttpClient(HttpClient httpClient, HttpClientHandler httpClientHandler, DelegatingHandler[] handlers)
   at Microsoft.Bot.Connector.ConnectorClient..ctor(Uri baseUri, DelegatingHandler[] handlers) in D:\a\1\s\libraries\Microsoft.Bot.Connector\ConnectorClient.cs:line 132
   at Microsoft.Bot.Builder.Integration.MessageSerializerSettings.Create() in D:\a\1\s\libraries\Microsoft.Bot.Builder\Integration\MessageSerializerSettings.cs:line 14
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase..cctor() in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandlerBase.cs:line 18
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandler.ProcessMessageRequestAsync(HttpRequest request, IAdapterIntegration adapter, BotCallbackHandler botCallbackHandler, CancellationToken cancellationToken) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandler.cs:line 20
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase.HandleAsync(HttpContext httpContext) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandlerBase.cs:line 60
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

As you can see, there are some questionable character(s) in the string `Darwin18.2.0DarwinKernelVersion18.2.0ThuDec20204653PST2018rootxnu-4903.241.11/RELEASE_X86_64`. In this case, the problem is the `/` character.

## To Reproduce
⚠️ This apparently does not happen 100% of the time and may depend on the details of the platform ⚠️ 

1. Be on MacOSX
2. Run a .NET Core bot
3. Send the bot an activity that causes it to initialize the `ConnectorClient` class
4. Observe the exception above

## Expected behavior
Any platform specific details put into the header are scrubbed of any illegal characters.

## Additional context
This looks to be a bug in the underlying `ServiceClient` class from AutoRest. It may just be that the `Microsoft.Bot.Builder.Connector` packages needs to update to a newer version of that SDK to fix this or there may need to be an issue filed with that team.

[bug]

**Comment by johnataylor** [comment]
This looks like it's the fix on the underlying ServiceClient back in early Nov:
https://github.com/Azure/azure-sdk-for-net/pull/4986

Also looks like they added a unit test for almost exactly this same platform string.

The fix on our side is to update the Package "Microsoft.Rest.ClientRuntime" Version="2.3.13" which dates form 7 months ago to "2.3.20" which was published 10 days ago.

We should also add a catch around the code in ConnectorClient.CustomInitialize just in case we hit a similar problem.

**Comment by johnataylor** [comment]
We checked this for 4.3.2 package should be available now
