### ISSUE TITLE
Facebook - Activity Exceptions: Value cannot be null. Parameter name: invalid activity-missing Conversation.Id

### ISSUE THREAD

**Issue by jamsoft** [Microsoft/botbuilder-dotnet#1443]
## Version
4.2.2

## Describe the bug
It seems a conversation arrived via the Facebook channel that was potentially missing key data.  I can't tell if the BotFramework got things wrong or something went wrong on the Facebook side

The first exception was dealing with a missing From details (which is understandable as I believe it started in the Web Chat Plugin that doesn't start new conversation with a user opt-in thus allowing access to the users profile data).

`Value cannot be null. Parameter name: invalid activity-missing From.Id`

Occured on this line:
`var userState = await _accessors.AAUserStateAccessor.GetAsync(turnContext, () => new AAUserState(), cancellationToken);`

The code I have written to handle exceptions contains this:

```
await _accessors.ConversationState.LoadAsync(turnContext, false, cancellationToken);
await _accessors.ConversationState.ClearStateAsync(turnContext, cancellationToken);
await _accessors.ConversationState.SaveChangesAsync(turnContext, true, cancellationToken);
```

So then the next exception in the stack was

Value cannot be null. Parameter name: invalid activity-missing Conversation.Id
This occured on this line:
`await _accessors.ConversationState.LoadAsync(turnContext, false, cancellationToken);`

## To Reproduce
1. Start a new conversaion via Web Chat Plugin

I can understand the `From` property being null due to the optin issues on Facebook when using the Web Chat Plugin but I'm not sure that it makes sense that the ConversationId is null.

I have now also updated this particular bot to v4.3.1 of the SDK.

[bug]

**Comment by EricDahlvang** [comment]
I've been unable to reproduce this issue.  Please share the following, so we can investigate further:

 - Bot Handle
 - Microsoft App Id for the bot
 - UTC Time for when the Exception occurred

**Comment by jamsoft** [comment]
Not entirely sure what you mean by Bot Handle (did you mean the name of the bot registration? If so that is autoagentbot).

The MS app Id is "9bb3eb37-cea6-490e-8639-5e6248e6f246"

The POST to the bot the caused the error was at 2019-03-11T17:36:41.0249261Z

The first error in that POST was invalid activity-missing From.Id at 2019-03-11T17:36:41.6730105Z

**Comment by jamsoft** [comment]
Not entirely sure what you mean by Bot Handle (did you mean the name of the bot registration? If so that is autoagentbot).

The MS app Id is "9bb3eb37-cea6-490e-8639-5e6248e6f246"

The POST to the bot the caused the error was at 2019-03-11T17:36:41.0249261Z

The first error in that POST was invalid activity-missing From.Id at 2019-03-11T17:36:41.6730105Z

**Comment by EricDahlvang** [comment]
Our logs only indicate there was an exception in the bot.  

There is nothing in the Bot Framework Facebook Connector Service removing From.Id or Conversation.Id from a message before sending it to the bot.  Either 1) there is an issue with the Facebook Chat Plugin or 2) something is modifying the message in the bot or 3) the message coming in is not a 'normal' or expected message from a user and directed towards a conversation.  

More information is required in order to determine what is happening.  Can you log the entire activity that is received when this exception occurs?  Along with a complete stack trace.

Do you have Application Insights configured for the bot, and the web application hosting the bot?  This should provide more information.
 
Bot: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0#enable-analytics
Web Application: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net

**Comment by jamsoft** [comment]
Hi Eric, sorry for no reply so far I've been utterly snowed under. I should have an opportunity to dig all this out for you tomorrow. We do have AI all setup and working so we're all good.

Thanks for your time so far.

**Comment by jamsoft** [comment]
Does this help?

name: invalid activity-missing From.Id
ai.snapshot.stampid | uksouth-ohgm3yzm66bru
ai.snapshot.id | 1b148b70664143bd858ab32b4906bc74

System.ArgumentNullException: at Microsoft.Bot.Builder.UserState.GetStorageKey (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at Microsoft.Bot.Builder.BotState+<LoadAsync>d__4.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Microsoft.Bot.Builder.BotState+BotStatePropertyAccessor`1+<GetAsync>d__7.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at AutoAgent.Bots.AutoAgentBot+<OnTurnAsync>d__10.MoveNext (AutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullAutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\AutoAgent\AutoAgent\Bots\AutoAgentBot.csAutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 202)

Value cannot be null. Parameter name: invalid activity-missing Conversation.Id
ai.snapshot.id | 7532f238aeec4dc98695260f11e04150
ai.snapshot.stampid | uksouth-ohgm3yzm66bru

System.ArgumentNullException: at Microsoft.Bot.Builder.ConversationState.GetStorageKey (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at Microsoft.Bot.Builder.BotState+<LoadAsync>d__4.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at AutoAgent.Bots.AutoAgentBot+<OnTurnAsync>d__10.MoveNext (AutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullAutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\AutoAgent\AutoAgent\Bots\AutoAgentBot.csAutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 381) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Microsoft.Bot.Builder.AutoSaveStateMiddleware+<OnTurnAsync>d__7.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Microsoft.Bot.Builder.MiddlewareSet+<ReceiveActivityWithStatusAsync>d__3.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Microsoft.Bot.Builder.BotAdapter+<RunPipelineAsync>d__13.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

I've actually not seen this particular error reoccur again yet. So not sure what conclusion to draw from that at the moment.

**Comment by jamsoft** [comment]
@EricDahlvang I've just had the error again ... when I switched a facebook messenger thread to Done in a handover scenario ... here is the stack trace:

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.abe08c1a6b4142cba7502af181bf5667.Exception","time":"2019-03-20T15:57:35.4001970Z","iKey":"abe08c1a-6b41-42cb-a750-2af181bf5667","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"LapJam","ai.operation.id":"e75d420a7ea5a44eb53db8e28e851207","ai.operation.parentId":"|e75d420a7ea5a44eb53db8e28e851207.8a8ab86_8a8ab87_5.7f6ec90b_","ai.operation.name":"POST ","ai.location.ip":"40.121.92.251","ai.internal.sdkVersion":"dotnet:2.9.1-26108","ai.internal.nodeName":"LAPJAM"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"exceptions":[{"id":29939153,"outerId":0,"typeName":"System.ArgumentNullException","message":"Value cannot be null.\r\nParameter name: invalid activity-missing Conversation.Id","hasFullStack":true,"parsedStack":[{"level":0,"method":"Microsoft.Bot.Builder.ConversationState.GetStorageKey","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\ConversationState.cs","line":30},{"level":1,"method":"Microsoft.Bot.Builder.BotState+<LoadAsync>d__4.MoveNext","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotState.cs","line":64},{"level":2,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":3,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":4,"method":"Microsoft.Bot.Builder.BotState+BotStatePropertyAccessor`1+<GetAsync>d__7.MoveNext","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotState.cs","line":305},{"level":5,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":6,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":7,"method":"Microsoft.Bot.Builder.Dialogs.DialogSet+<CreateContextAsync>d__9.MoveNext","assembly":"Microsoft.Bot.Builder.Dialogs, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\DialogSet.cs","line":92},{"level":8,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":9,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":10,"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":11,"method":"AutoAgent.Bots.AutoAgentBot+<OnTurnAsync>d__9.MoveNext","assembly":"AutoAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"C:\\Code\\autoagent\\bot-core\\AutoAgent\\AutoAgent\\Bots\\AutoAgentBot.cs","line":175},{"level":12,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":13,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":14,"method":"Microsoft.Bot.Builder.AutoSaveStateMiddleware+<OnTurnAsync>d__7.MoveNext","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\AutoSaveStateMiddleware.cs","line":60},{"level":15,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":16,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":17,"method":"Microsoft.Bot.Builder.MiddlewareSet+<ReceiveActivityWithStatusAsync>d__3.MoveNext","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\MiddlewareSet.cs","line":55},{"level":18,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":19,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0},{"level":20,"method":"Microsoft.Bot.Builder.BotAdapter+<RunPipelineAsync>d__13.MoveNext","assembly":"Microsoft.Bot.Builder, Version=4.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","fileName":"D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotAdapter.cs","line":167}]}],"properties":{"AspNetCoreEnvironment":"Local-Development","DeveloperMode":"true"}}}}
AutoAgent.Bots.AutoAgentBot:Error: **Exception caught : System.ArgumentNullException: Value cannot be null.
Parameter name: invalid activity-missing Conversation.Id**
   at Microsoft.Bot.Builder.ConversationState.GetStorageKey(ITurnContext turnContext) in D:\a\1\s\libraries\Microsoft.Bot.Builder\ConversationState.cs:line 30
   at Microsoft.Bot.Builder.BotState.LoadAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotState.cs:line 64
   at Microsoft.Bot.Builder.BotState.BotStatePropertyAccessor`1.GetAsync(ITurnContext turnContext, Func`1 defaultValueFactory, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotState.cs:line 305
   at Microsoft.Bot.Builder.Dialogs.DialogSet.CreateContextAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogSet.cs:line 92
   at AutoAgent.Bots.AutoAgentBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Code\autoagent\bot-core\AutoAgent\AutoAgent\Bots\AutoAgentBot.cs:line 175
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 60
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167
Microsoft.Bot.Builder.Integration.IAdapterIntegration:Information: Sending activity.  ReplyToId: IBNkZ7wWg2d
Exception thrown: 'System.NullReferenceException' in Microsoft.Bot.Connector.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HLLD9H2FQ2PN", Request id "0HLLD9H2FQ2PN:00000001": An unhandled exception was thrown by the application.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, Activity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsEx.cs:line 138
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 315
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 196
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 179
   at AutoAgent.Startup.<>c__DisplayClass11_1.<<ConfigureServices>b__5>d.MoveNext() in C:\Code\autoagent\bot-core\AutoAgent\AutoAgent\Startup.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 177
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity identity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 233
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 204
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandler.ProcessMessageRequestAsync(HttpRequest request, IAdapterIntegration adapter, BotCallbackHandler botCallbackHandler, CancellationToken cancellationToken) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandler.cs:line 39
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase.HandleAsync(HttpContext httpContext) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandlerBase.cs:line 60
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by EricDahlvang** [comment]
I apologize for the delayed response.  I'm investigating this more thoroughly.   Can you log the ChannelData of the incoming message when this occurs?

**Comment by EricDahlvang** [comment]
@jamsoft I think the issue here is that the handover protocol 'event' activities do not contain a conversation.id or from.id, since they are notification events from the service to the bots.

One possible way to work around this is to eliminate the BotMessageHandler, and go with a Controller approach similar to: https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/13.core-bot/Controllers/BotController.cs  This is the standard we are moving our sample towards.  

If you are available to work more directly with me on these Messenger Handover protocol issues, please email me at the address on my profile.

**Comment by EricDahlvang** [comment]
We've determined two issues exist within the Bot Framework Facebook Connector service:

1) standby events were not being sent to bots tied to secondary apps

2) during the handover process, when control is passed, the connector service is sending conversationUpdate event that contains no conversation.id

These issues have been addressed, and the fix is in the pipeline for release.

Thank you for reporting this issue.
