### ISSUE TITLE
ChoicePrompt with Attachment input

### ISSUE THREAD

**Issue by wrende** [Microsoft/botbuilder-dotnet#1575]
## Version
4.2.2

## Describe the bug
ChoicePrompt crashes on attachment input. FindChoices is unable to handle attachments.

>System.ArgumentNullException: Value cannot be null.
Parameter name: utterance
   at Microsoft.Bot.Builder.Dialogs.Choices.Find.FindChoices(String utterance, IList`1 choices, FindChoicesOptions options)
   at Microsoft.Bot.Builder.Dialogs.Choices.ChoiceRecognizers.RecognizeChoices(String utterance, IList`1 list, FindChoicesOptions options)
   at Microsoft.Bot.Builder.Dialogs.ChoicePrompt.OnRecognizeAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)

## To Reproduce
ChoicePrompt is unable to handle attachments as an answer, this will result in an error.

## Expected behavior
When an attachment is send as an answer to a ChoicePrompt, the FindChoices method will find no match and the RetryPrompt of the ChoicePrompt will be triggered.

[bug]

**Comment by tdurnford** [comment]
The ChoicePrompt's default validator is checking the incoming activity's text attribute to ensure it is a valid choice; however, attachment uploads do not have a text value. Consequently, the prompt validator throws a 'Value cannot be null' error when the user sends an attachment in response to a ChoicePrompt because of the missing text value. You can either create a custom validator for your prompt or use an AttachmentPrompt. 

For more details on [Custom Prompt Validators](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp#custom-validation) and [Attachment Prompts](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.attachmentprompt?view=botbuilder-dotnet-stable), please refer to the Microsoft BotBuilder Documentation.
