### ISSUE TITLE
Microsoft.IdentityModel.Clients.ActiviteDirectory.AuthenticationContext Constructor missing when updated

### ISSUE THREAD

**Issue by rosskyl** [microsoft/botbuilder-dotnet#2091]
## Version
C# 4.4.5 on .net core 2.2

## Describe the bug
The `Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext` constructor used by `Microsoft.Bot.Connector` is wrong if that nuget package is installed in an updated version. It gives an error that the method is not found in Azure.

## To Reproduce
1. Create a new bot template project
2. Install the nuget package `Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext` version 5 or higher
3. Deploy the bot to Azure
4. The bot will not work and an error will be thrown when you use `turnContext.SendActivityAsync`

## Expected behavior
The updated version requires an `IHttpClientFactory` instead of an `HttpClient`.

## Additional context
Exception message: 
`Method not found: 'Void Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(System.String, Boolean, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache, System.Net.Http.HttpClient)'.`

Stack trace:
```
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator..ctor(ClientCredential clientCredential, OAuthConfiguration configurationOAuth, HttpClient customHttpClient)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<>c__DisplayClass8_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at EchoBot1.Bots.EchoBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in C:\Users\kross\source\repos\EchoBot1\EchoBot1\Bots\EchoBot.cs:line 23
```

[bug]

**Comment by rosskyl** [comment]
The workaround is to use version 4.5.1 of  `Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext`.

**Comment by Kaiqb** [comment]
Closing the issue as it was resolved by rosskyl.
