### ISSUE TITLE
In proactive callback, adapter.SendActivitiesImplementation throws null argument exception.

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#234]
I'm getting a null argument exception reminiscent of closed security issue  #226 . This sample had been working prior to the big refactoring earlier this week. (I'm testing my bot via the emulator.)

Here's the exception details, followed by my code, which fails within `await adapter.ContinueConversation(reference, onReady);`

```text
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Bot.Builder
  StackTrace:
   at Microsoft.Bot.Builder.Adapters.BotFrameworkAdapter.<SendActivitiesImplementation>d__7.MoveNext() in C:\Users\v-jofing\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 78
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotAdapter.<RunPipeline>d__6.MoveNext() in C:\Users\v-jofing\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Core\BotAdapter.cs:line 93
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotAdapter.<ContinueConversation>d__8.MoveNext() in C:\Users\v-jofing\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Core\BotAdapter.cs:line 122
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProactiveMessaging.SubscribeMiddleware.<CreateContextForUser>d__4.MoveNext() in C:\Users\v-jofing\source\repos\botbuilder-dotnet-writing\WikiSnippets\ProactiveMessaging\SubscribeMiddleware.cs:line 53
```

```csharp
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Middleware;
using Microsoft.Bot.Schema;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProactiveMessaging
{
    public class SubscribeMiddleware : IMiddleware, IReceiveActivity
    {
        private BotAdapter adapter;

        private readonly Dictionary<string, ConversationReference> conversations =
            new Dictionary<string, ConversationReference>();

        public async Task ReceiveActivity(IBotContext context, MiddlewareSet.NextDelegate next)
        {
            var utterance = context.Request.AsMessageActivity()?.Text.Trim().ToLower();
            if (string.Equals(utterance, "subscribe"))
            {
                if (adapter is null)
                {
                    adapter = context.Adapter;
                }
                var reference = context.ConversationReference;
                var userId = reference.User.Id;
                conversations[reference.User.Id] = reference;

                SubscribeUser(userId);
                context.Reply("Thank You! We will message you shortly.");

                // Short circuit the messages pipeline.
                return;
            }

            await next();
        }

        private void SubscribeUser(string userId)
        {
            CreateContextForUser(userId, async (IBotContext context) =>
            {
                context.Reply("You've been notified!");
                await Task.Delay(2000);
            });
        }

        private async void CreateContextForUser(string userId, Func<IBotContext, Task> onReady)
        {
            var reference = conversations[userId];
            await adapter.ContinueConversation(reference, onReady);
        }
    }
}
```

**Comment by JonathanFingold** [comment]
Post M2 merge, we have this:
```csharp
public virtual async Task ContinueConversation(ConversationReference reference, Func<IBotContext, Task> callback)
{
    throw new NotImplementedException("Proactive conversation support is not currently implemented in M2.");
}
```
