### ISSUE TITLE
[Adaptive] Resource explorer throws exception for empty projectFile

### ISSUE THREAD

**Issue by GewoonMaarten** [microsoft/botbuilder-dotnet#2346]
## Version
4.5.0-Preview-2019-05-02-02

## Describe the bug
When I deployed one of the samples to a clean Azure App service and connected Bot service testing environment the ResourceExplorer threw an ArgumentNullException because the projectFile was null.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: projectFile
   at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.ResourceExplorer.LoadProject(String projectFile, String[] ignoreFolders, Boolean monitorChanges)
   at Microsoft.BotBuilderSamples.Startup.ConfigureServices(IServiceCollection services) in C:\Users\maart\source\repos\BotBuilder-Samples\experimental\adaptive-dialog\declarative\60.AdaptiveBot\Startup.cs:line 35

--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

## To Reproduce
1. Download latest sample from https://github.com/microsoft/BotBuilder-Samples
2. Deploy sample 60.AdaptiveBot (I did it via Visual Studio 2019)
3. Set ASPNETCORE_DETAILEDERRORS to true

## Expected behavior
I expected to see the index.html but get the error message instead.

[bug]

**Comment by GewoonMaarten** [comment]
somebody opened a similar issue on https://github.com/microsoft/BotBuilder-Samples/issues/1581 which was resolved.

**Comment by GewoonMaarten** [comment]
I added this nuget file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="BotBuilder.myget.org" value="https://botbuilder.myget.org/F/botbuilder-declarative/api/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
But i still get the error.

**Comment by GewoonMaarten** [comment]
@tomlm Thanks for the good work! I appreciate it. Is pull request #2378 going to be merged for a nightly build in the near future or should I wait until the 4.6 release?

**Comment by GewoonMaarten** [comment]
Okay, the previous error has been resolved. But now I am getting a different error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.PathUtils.NormalizePath(String ambigiousPath)
   at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.FolderResourceProvider..ctor(String folder, Boolean includeSubFolders, Boolean monitorChanges)
   at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.ResourceExplorer.LoadProject(String projectFile, String[] ignoreFolders, Boolean monitorChanges)
   at ArenABot.HospitalityBot.Startup.ConfigureServices(IServiceCollection services) in C:\Users\maart\source\repos\ArenAChatbot\src\ArenABot.Bot\Startup.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

I will close this issue (as it has been fixed) and open a new one.
