### ISSUE TITLE
[Adaptive] NullReferenceException at Microsoft.Bot.Builder.PathUtils.NormalizePath

### ISSUE THREAD

**Issue by GewoonMaarten** [microsoft/botbuilder-dotnet#2465]
## Version
Version: **4.6.0-Daily-2019-08-31-01**
## Describe the bug
When I deployed one of the samples to a clean Azure App service and connected Bot service testing environment the Microsoft.Bot.Builder.PathUtils.NormalizePath threw a NullReferenceException. 

## To Reproduce
1. Download sample 60.AdaptiveBot from https://github.com/microsoft/BotBuilder-Samples
2. Update versions to 4.6.0-Daily-2019-08-31-01
3. Deploy sample 60.AdaptiveBot (I did it via Visual Studio 2019)
4. Set ASPNETCORE_DETAILEDERRORS to true
5. See error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.PathUtils.NormalizePath(String ambigiousPath)
   at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.FolderResourceProvider..ctor(String folder, Boolean includeSubFolders, Boolean monitorChanges)
   at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.ResourceExplorer.LoadProject(String projectFile, String[] ignoreFolders, Boolean monitorChanges)
   at ArenABot.HospitalityBot.Startup.ConfigureServices(IServiceCollection services) in C:\Users\maart\source\repos\ArenAChatbot\src\ArenABot.Bot\Startup.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

## Expected behavior
I expected to see the index.html but get the error message instead.

## Additional context
My guess would be that ContentRootPath from HostingEnvironment returns a different path in azure than it does locally which is not the path expected by the library. But I could find any proof to back it up.
[bug]

**Comment by vishwacsena** [comment]
Fixed in latest bits in 4.Future.
