### ISSUE TITLE
Microsoft.Bot.Builder.Integration.AspNet.Core in 4.6.0-preview1 throwing ArgumentNullException

### ISSUE THREAD

**Issue by beauzeaux** [microsoft/botbuilder-dotnet#2762]
##  Version
4.6.0-preview1 (Both `Microsoft.Bot.Builder` and `Microsoft.Bot.Builder.Integration.AspNet.Core`)

## Describe the bug
When request lands on service, `ArgumentNullException` is thrown & results in 500 response. 

## To Reproduce
[Reproduction Repo (adapted echo bot)](https://github.com/beauzeaux/botbuilder-netcore-integration-regression)

## Expected behavior
Request goes to registered activity handler

## Screenshots
```
System.ArgumentNullException: Value cannot be null.
Parameter name: activity
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 296
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandler.ProcessMessageRequestAsync(HttpRequest request, IAdapterIntegration adapter, BotCallbackHandler botCallbackHandler, CancellationToken cancellationToken) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandler.cs:line 42
   at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase.HandleAsync(HttpContext httpContext) in D:\a\1\s\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\BotMessageHandlerBase.cs:line 61
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 9.8179ms 500 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 9.8179ms 500
```
## Additional context
Issue was not present in MyGet version 4.6.0-preview-191002-1

[bug]

**Comment by EricDahlvang** [comment]
This is a regression from https://github.com/microsoft/botbuilder-dotnet/commit/77e91acc250f88a41549199ab543e2931cb898e4#diff-11fda0f4e57fe29d77b11a003ef770b7R21

Adding `memoryStream.Position = 0;` fixes the issue.

**Comment by beauzeaux** [comment]
Thanks for the quick turnaround on this one!
