### ISSUE TITLE
Prompting examples in Wiki don't work unless BatchOutput middleware is added

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#293]
This prereq is not mentioned in the setup/instructions for prompting

**Comment by cleemullins** [comment]
I'm pulling those out today. The direct send approach seems far preferable.

**Comment by cleemullins** [comment]
Addressed in PR #303. Steve will also be removing this from the Node side.

**Comment by brandonh-msft** [comment]
@cleemullins please don't close an issue unless the PR's been merged...

**Comment by joescars** [comment]
Steps to reproduce:

 - follow [getting started](https://github.com/Microsoft/botbuilder-dotnet/wiki) 
 - replacing context.reply with context.SendActivity
 - replace OnReceiveActivity with example code here: https://github.com/Microsoft/botbuilder-dotnet/wiki/Prompting-Users#textprompt 
 adding reference to
 using Microsoft.Bot.Builder.Core.Extensions;
using Microsoft.Bot.Builder.Prompts
Prompts;
 - run the app, connect via emulator and try chatting... 

```
System.InvalidOperationException
  HResult=0x80131509
  Message=BatchOutputMiddleware does not appear to be setup.
  Source=Microsoft.Bot.Builder.Core.Extensions
  StackTrace:
   at Microsoft.Bot.Builder.Core.Extensions.BatchOutputExtensions.Batch(IBotContext context) in C:\Code\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Core.Extensions\BatchOutput.cs:line 184
   at Microsoft.Bot.Builder.Prompts.BasePrompt`1.Prompt(IBotContext context, IMessageActivity activity) in C:\Code\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Prompts\BasePrompt.cs:line 79
   at Microsoft.Bot.Builder.Prompts.BasePrompt`1.Prompt(IBotContext context, String text, String speak) in C:\Code\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Prompts\BasePrompt.cs:line 71
   at Microsoft.Bot.Samples.HelloBot.<GetTextUsingPrompt>d__3.MoveNext() in C:\Code\botbuilder-dotnet\HelloWorld-Prompt\HelloBot.cs:line 37
```

**Comment by brandonh-msft** [comment]
@cleemullins 
I see you merged to master; did you verify that @joescars' use case functions?

cc @tomlm @cmayomsft @billba

**Comment by cleemullins** [comment]
The example code is broken (we're working on it), but I have confirmed that Prompts do not need the batch middleware any longer. 

The tests around this have all been updated.
