### ISSUE TITLE
Adaptive HttpRequest body does not interpret property for body field

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#3219]
‘Body’ is taking the property string literally "@{dialog.httpbody}".  It seems that Body requires a JObject.  In turn, Json is throwing an exception  
 
Example:
``` 
new Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.HttpRequest()
                                    {
                                        // Set response from the http request to turn.httpResponse property in memory.
                                        ResultProperty = "dialog.httpResponse",
                                        Url = apiUrl,
                                        Method = HttpRequest.HttpMethod.POST,
                                        Body = "@{dialog.httpbody}",
                                        ResponseType = HttpRequest.ResponseTypes.None
                                    },
```

$exception              {System.InvalidOperationException: The parent is missing.
   at Newtonsoft.Json.Linq.JToken.Replace(JToken value)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.HttpRequest.ReplaceJTokenRecursively(DialogContext dc, JToken token)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.HttpRequest.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)

**Comment by vishwacsena** [comment]
I debugged this and the core issue seems to be twofold. 
1. We at the moment do not support body to be set to an expression. We however should. I tried this snippet and it worked great 
```C# 
// Single command running with a copy of the original data
client.DefaultRequestHeaders.Clear();

JToken instanceBody = null;
if (this.Body != null)
{
    try
    {
        // This is to support body being set to a memory path.
        var instanceBodyAsValue = await new TextTemplate(this.Body.ToString()).BindToData(dc.Context, dc.GetState()).ConfigureAwait(false);
        instanceBody = JToken.Parse(instanceBodyAsValue);
    }
    catch (Exception ex)
    {
        instanceBody = (JToken)this.Body.DeepClone();
    }
}
```

Issue #2: we should consider adding headers without validtion so things like adding content-type does not blow up (it does with a .Add())

```C#
// Set headers
if (instanceHeaders != null)
{
    foreach (var unit in instanceHeaders)
    {
        client.DefaultRequestHeaders.TryAddWithoutValidation(
            await new TextTemplate(unit.Key).BindToData(dc.Context, dc.GetState()).ConfigureAwait(false),
            await new TextTemplate(unit.Value).BindToData(dc.Context, dc.GetState()).ConfigureAwait(false));
    }
}
```
