### ISSUE TITLE
Declaritive Libraries fail to make HTTP requests within App Services

### ISSUE THREAD

**Issue by kishanhickman** [microsoft/botbuilder-dotnet#3504]
## Describe the bug
When I try to make a http requests through the JSON files produced by Composer, this works fine locally, but fails when published in an Azure App Service.

I have tested using a different end point separate to API app we have in azure (changing the json config) - failed  

I have tried to change various network settings within the app service, but it allows all traffic with all ports and regardless of the many attempts to change things, it makes no differnece.

I have then added some code in the same bot which the dialog files are hosted in, to manally make a HTTP request via HTTP client in the OnTurn Async method of our bot  - this WORKS

So it leads me to believe that the issue isnt a network layer, accesss isues, as HTTP clients works with manual code in the same bot/app service.  Its only when I used apative dialogs via the declaritve dlls and Json config that it fails. 

Here is it working with a standard http client request

*Removed*

Here is it failing when I try to do it via this code in the json file

*Removed*

As you can see by that screenshot I have commented out another mock api which I used to make sure it wasnt our internal api that was causing the problem.

We have also tested our internal api with postman and it works fine as expected.

## To Reproduce
1. Deploy the app and get it up and running
2. load the bot framework emulator with correct app service settigns
3.  Type "challenge" to get the bot to sstart and ask you for a contravention code
4.  Enter "85"
5.  You will see the error if you are connecting to the bot on azure, not locally

## Expected behavior
it should produce some JSON which shows it recieved fedeback and the key thing is we want the content to be "True" for this api call 

## Screenshots
Here is a screen of it failing

![image](https://user-images.githubusercontent.com/5497558/76009627-6ca02380-5f09-11ea-889f-0a76785f4d88.png)

Here is the stack trace;

 ```
An attempt was made to access a socket in a way forbidden by its access permissions. | at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
 at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
 at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
 at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.HttpRequest.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.BeginDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogManager.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken)
 at Bot.Skill.Parking.Bots.ComposerBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\kishan\source\repos\Max\Bot.Skill.Parking\Bots\ComposerBot.cs:line 75
 at Microsoft.Bot.Solutions.Skills.SkillMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"
```

**One thing to make clear - every other part of the dialog work - it is ONLY Http Requests that cause this issue remotely in azure, yet works fine locally. Given that I can make a http request in the sasme app service with my own code, it suggests to me there is a bug or a settign I dont know about to make that work with adaptive dialogs (declaritive)**

This is the last hurdle we have to go live and I would greatly apprecaite any help.  Even if that is a workaround to use our own code to make our own HTTP request calls that can be fed into the dialog as required 

**Here is the code**

*Removed*

Many Thanks

Kishan

[bug]

**Comment by stevengum** [comment]
@CoHealer can you have one of the support engineers get a repro running with the code provided from @kishanhickman?

**Comment by CoHealer** [comment]
Assigning @v-kydela. Kyle, please assist and attempt a repro as requested above.

**Comment by v-kydela** [comment]
@CoHealer - I'm sorry but I won't be able to repro this until my Azure subscription blockers are resolved

@kishanhickman - I've removed your code because it contained your password. If you'd like to provide sample code in the future then please make sure you remove sensitive information from it. It's also a good idea to create a minimal example when trying to reproduce a bug rather that sharing a whole project. I also removed two of your screenshots because they contained an authorization token that may also be sensitive. It's also worth noting that code should be posted using Markdown code-formatting conventions and not screenshots.

I've had a look at the [source code](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs#L248) and I didn't notice any funny business that seems like it should prevent the request from working. The biggest difference I see is that the SDK code is using `PostAsync` instead of `SendAsync`. That's not likely to cause issues since your sample code seemed pretty similar to the [implementation](https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/HttpClient.cs#L293-L299) of `PostAsync`, but all the same you might try modeling your sample request to match the way the SDK sends the request to see if you can reproduce the error manually.

**Comment by v-kydela** [comment]
@kishanhickman - Yes I understand that it's working locally but not when deployed. As I explained, it's beyond my power to test deployment issues at the moment. Perhaps my team will be able to unblock me or decide to assign someone else.

In the meantime, you may want to see if you can isolate your problem and make it easier to reproduce. The reason it's a good idea to create a minimal example isn't just because we can encounter the problem faster once we run the project. A minimal example also helps isolate what the problem actually is. Also, we couldn't run your project anyway because it had a local dependency that you hadn't included in the zip.

You say you encountered a similar issue when trying to deploy the experimental echo bot sample. Do you mean [the declarative echo bot sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/declarative/10.EchoBot)? That problem may be worth looking into as well.

**Comment by kishanhickman** [comment]
Yes that was the bot

**Comment by v-kydela** [comment]
I have become unblocked and have performed your repro steps. I can reproduce your error when I use your app service, but when I deploy your code to my app service it works fine:

![image](https://user-images.githubusercontent.com/41968495/76129353-163fed00-5fbc-11ea-992b-58cb669009c0.png)

It looks like the problem likely has more to do with your Azure resources than the SDK. We will need to investigate the difference between your app service and mine if we are to discover the problem. My app service was created during the deployment of a web app bot resource. My resources are all in West US 2 and use a free pricing tier. Here are my app service's general settings:

![image](https://user-images.githubusercontent.com/41968495/76130280-1ee5f280-5fbf-11ea-920f-7bd32e031c2d.png)

How does this compare to yours?

**Comment by kishanhickman** [comment]
Hi Kyle 

The only difference I can see if that your using West is for your app service and I’m using uksputh.  Let me try west us 2 today and get back to you

Other settings look identical how do I check the iOS version without code (ie inside azure)?

**Comment by kishanhickman** [comment]
Hi Kyle 

When I deploy this to westus with the deploy script it does work as expected - so thanks again for your help.  

The only issue I see with this is GDPR and data protection objections with clients.  I wonder who I can raise this with on the Azure front to get it working for uksouth?

**Comment by v-kydela** [comment]
@kishanhickman - You said you are able to send HTTP requests from a web app in UK south so long as those requests aren't coming from an adaptive dialog, right? If you were to take this to the Azure app service team they wouldn't know what to do with it because to them it would appear to be a Bot Framework problem. There is still work for us to do to isolate the bug and discover what's happening in the SDK to cause this discrepancy. Are you willing to help create a minimal verifiable example?

By the way, I'm no longer able to access your bot. Did you shut down any of your Azure resources over the weekend?

**Comment by kishanhickman** [comment]
Hi Kyle

Yes ill try to get you a minimal verifiable example across tomorrow PM
(GMT).

Best Regards,


*Kishan Hickman*

*m  *+44 7944 325 218
*e   *kishan.hickman@gmail.com
*w  *http://uk.linkedin.com/in/kishanhickman

   -

Head of Development ★ CTO ★ Software Development ★ Web Technologist ★ IT
Strategy

**Comment by v-kydela** [comment]
@kishanhickman - Are you still able to talk to your deployed bot in the Emulator?

**Comment by kishanhickman** [comment]
Hi Kyle

I have re-deployed this to uksouth (trying to fix a locale issue) and this time it seems to have worked and I dont get the HTTPClient blocking issue.  I have deployed twice to uksouth and both times it works -  so I think we can close that and assume that this was a temporary issue.

Thanks again for all your help
