### ISSUE TITLE
Microsoft.Bot.Builder - "Object reference not set to an instance of an object" 

### ISSUE THREAD

**Issue by Eli2590** [microsoft/botbuilder-dotnet#3812]
## Version
3.30

## Describe the bug
After filling form user is asked for a question: "Did you get the information you were looking for?"
There are two options to this answer: 'Yes' or 'No'. Choosing 'Yes' should complete the form and choosing 'No' should continue the form. When writing in the chat different values then the two above, it recognizes that the value is not an option and asks to choose one of the options above, except the case that the value is "No someText" or "Yes someText". In this case I get an exception
"Object reference not set to an instance of an object.":

"Exception": Failure to complete form. Exception:: at HandleFormException in C:\source\Src\Tools\KusBot\Dialogs\FormDialog.cs: line 64
***
[Microsoft.Bot.Builder.FormFlow.FormCanceledException`1[[KusBot.Forms.ChangePermissionForm, KusBot, Version=1.0.7415.27440, Culture=neutral, PublicKeyToken=null]]]
***
Object reference not set to an instance of an object.
Microsoft.Bot.Builder.FormFlow.FormCanceledException`1[KusBot.Forms.ChangePermissionForm]: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.FormFlow.Advanced.Language.Normalize(String value, CaseNormalization normalization)
   at Microsoft.Bot.Builder.FormFlow.Advanced.Prompter`1.ExpandTemplate(String template, String currentChoice, String noValue, T state, IField`1 field, Object[] args, IList`1& buttons)
   at Microsoft.Bot.Builder.FormFlow.Advanced.Prompter`1.Prompt(T state, IField`1 field, Object[] args)
   at Microsoft.Bot.Builder.FormFlow.Advanced.FieldStep`1.<ProcessAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<>c__DisplayClass16_1.<<MessageReceived>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<MessageReceived>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<MessageReceived>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult()
   at KusBot.Dialogs.FormDialog.<CompleteForm>d__3.MoveNext() in C:\source\Src\Tools\KusBot\Dialogs\FormDialog.cs:line 39

## Expected behavior
I expect it to not recognize the value as an option and ask to choose one of the options above or to recognize "No someText" or "Yes someText" as "No" or "Yes" respectively.

## Screenshots
In case of entering value not from the list:
![image](https://user-images.githubusercontent.com/62258224/80314503-7bfd6800-87fa-11ea-9d96-b118eacfd8b7.png)

In case of choosing "Yes":
![image](https://user-images.githubusercontent.com/62258224/80314528-b961f580-87fa-11ea-8b5a-7963ad133d03.png)

In case of choosing "No":
![image](https://user-images.githubusercontent.com/62258224/80314561-f332fc00-87fa-11ea-8380-4d01342e42ff.png)

In case of entering "No someText":
![image](https://user-images.githubusercontent.com/62258224/80314627-3db47880-87fb-11ea-8bc4-36b70da15bea.png)
Then I saw the error in the traces

## Additional context

[bug]

**Comment by sgellock** [comment]
V3 SDK issue

**Comment by mdrichardson** [comment]
@Eli2590 I'm unable to replicate this. Can you:

1. Verify that you're using the latest V3 packages? `3.30.0`
2. Copy/paste your entire `FormDialog.cs` and any other relevant code?

Also note: It would be a good idea to start migrating to [Botframework v4](https://github.com/microsoft/botframework-sdk).
