### ISSUE TITLE
TeamsInfo.GetTeamDetailsAsync returns FORBIDDEN when invoking messaging extension from a channel

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/botbuilder-dotnet#3831]
## Version
4.8.0

## Describe the bug
When running TeamsInfo.GetTeamDetailsAsync() within a messaging extension I get back the following error when invoking the messaging extension from a channel:
```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass25_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.<>c__DisplayClass7_0.<<OnTurnAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at SolvionErdwin.AdapterWithErrorHandler.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in C:\Users\sbi\source\repos\Solvion-Erdwin\AdapterWithErrorHandler.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity claimsIdentity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at SolvionErdwin.Controllers.BotController.PostAsync() in C:\Users\sbi\source\repos\Solvion-Erdwin\Controllers\BotController.cs:line 45
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## To Reproduce
1. Within the bot add TeamDetails teamDetails = await TeamsInfo.GetTeamDetailsAsync(turnContext, turnContext.Activity.TeamsGetTeamInfo().Id, cancellationToken);
2. Run the bot and trigger the messaging extension in a channel

## Expected behavior
It should return the teamsDetails

[bug]

**Comment by hcyang** [comment]
hi @dmvtech, please take a look. thanks.

**Comment by clearab** [comment]
That looks like your bot isn't installed in that channel. This can happen for messaging extensions when the app is installed personally, but not in whatever group context the user is currently viewing when they trigger your extension. You can use the just-in-time installation request to attempt to install your bot in that context - https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

**Comment by stephanbisser** [comment]
Strange thing is that the bot is installed in that channel. But I will take a look at your link and see if that fixes the problem as it doesn't occur in every channel...

**Comment by clearab** [comment]
If that isn't it did the appId in the manifest change at some point? You could try manually removing/re-adding the app first to see if it resolves it for a channel where it is failing.

**Comment by stephanbisser** [comment]
Do you have a C# sample of using the just-in-time installation process @clearab so I can test that? App IDs and secrets didn't change and are the same in the manifest and the Bot Channels Registration, so that's not the issue

**Comment by cleemullins** [comment]
@clearab, can you update this please?

**Comment by clearab** [comment]
I don't have a sample of other than what is in the documentation I linked above - did you try manually removing/re-adding it to the channel, and if so did that resolve the issue?

Is the `turnContext.Activity.TeamsGetTeamInfo().Id` returning the correct Id for the team (it should be, but just want to check and see if that is potentially the issue).

**Comment by mrivera-ms** [comment]
@stephanbisser, could you please comment?

**Comment by stephanbisser** [comment]
Sorry for the delay. @clearab yes the ID is correct when doing tracing that...
I guess a sample of the JIT installation sample would help a lot

**Comment by stephanbisser** [comment]
I did solve the problem now and wrote down how to do that here: https://bisser.io/bot-framework-teams-messaging-extensions-walkthrough/

Basically I used the justInTimeInstall routine to check if the bot has been installed or not

**Comment by clearab** [comment]
Awesome write up, thanks for that!
