### ISSUE TITLE
QNAMakerDialog bug in 4.9.0

### ISSUE THREAD

**Issue by pavolum** [microsoft/botbuilder-dotnet#3881]
When you begin a QNAMakerDialog an exception of type System.Reflection.TargetInvocationException is thrown.

## Version
What package version of the SDK are you using.
4.9.0-rc1

## Describe the bug
When you begin a QNAMakerDialog an exception of type System.Reflection.TargetInvocationException is thrown (stack trace added below).

## Repro steps
trigger a QNAMakerDialog to begin

## Gary's findings (taken from email thread)
QnAMakerDialog has a property, LogPersonalInformation, which until recently was defaulted to false.  However, when the adaptive / non-adaptive QnAMaker dialogs were merged, this property was changes to default to “=settings.telemetry.LogPersonalInformation”.  This default was added to the adaptive version of the dialog to allow the setting to be set via app settings bot wide.
 
In and of itself this isn’t an issue – what appears to be the problem here is when the QnAMakerDialog tries to get the value for this property it is throwing instead of defaulting to false.
 
            return new QnAMaker(endpoint, options, HttpClient, this.TelemetryClient, this.LogPersonalInformation.GetValue(dc.State));
 
This appears to be due to the following;
 
1.	GetValue calls dialogStateManager.TryGetValue
2.	TryGetValue calls ResolveMemoryScope, which throws an ArgumentOutOfRangeException due to the fact that the memory scope doesn’t exist (https://github.com/microsoft/botbuilder-dotnet/blob/99ac54782b957eaf17c55bf44b89faee3de9142f/libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs#L153)
3.	This exception isn’t caught within TryGetValue, so instead of returning the default value, it throws instead.
 
I will defer to @Tom Laird-McConnell on the fix we should implement here, but the workaround I have in place (here -> https://github.com/microsoft/botbuilder-dotnet/blob/99ac54782b957eaf17c55bf44b89faee3de9142f/libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs#L179-L190), which is working for me, is to catch the exception in TryGetValue and return false.  This means that when used outside of the adaptive context the property will default to false, which means we don’t break anybody already using this dialog.
 
public bool TryGetValue<T>(string path, out T value)
        {
            value = default;
            path = TransformPath(path ?? throw new ArgumentNullException(nameof(path)));
 
            MemoryScope memoryScope;
            string remainingPath;
 
            try
            {
                memoryScope = ResolveMemoryScope(path, out remainingPath);
            }
            catch (ArgumentOutOfRangeException)
            {
                return false;
            }
 
            if (memoryScope == null)
            {
                return false;
            }

## Stack Trace
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''settings.telemetry.logPersonalInformation' does not match memory scopes:')
at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.ResolveMemoryScope(String path, String& remainingPath)
at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.TryGetValue[T](String path, T& value)
at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.TryGetValue(String key, Object& value)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at AdaptiveExpressions.Memory.ReflectionMemory.TryGetValue(String path, Object& value)
at AdaptiveExpressions.ExpressionFunctions.WrapGetValue(IMemory memory, String property, Options options)
at AdaptiveExpressions.ExpressionFunctions.Accessor(Expression expression, IMemory state, Options options)
at AdaptiveExpressions.ExpressionEvaluator.TryEvaluate(Expression expression, IMemory state, Options options)
at AdaptiveExpressions.Expression.TryEvaluate[T](IMemory state, Options options)
at AdaptiveExpressions.Expression.TryEvaluate[T](Object state, Options options)
at AdaptiveExpressions.Properties.ExpressionProperty`1.TryGetValue(Object data)
at AdaptiveExpressions.Properties.ExpressionProperty`1.GetValue(Object data)
at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.GetQnAMakerClientAsync(DialogContext dc)
at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.CallGenerateAnswerAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
at VirtualAssistantSample.Dialogs.MainDialog.RouteStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in C:\Users\pavolum\source\repos\botframework-solutions\samples\csharp\assistants\virtual-assistant\VirtualAssistantSample\Dialogs\MainDialog.cs:line 338
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
at VirtualAssistantSample.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\Users\pavolum\source\repos\botframework-solutions\samples\csharp\assistants\virtual-assistant\VirtualAssistantSample\Dialogs\MainDialog.cs:line 152
at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
at VirtualAssistantSample.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\pavolum\source\repos\botframework-solutions\samples\csharp\assistants\virtual-assistant\VirtualAssistantSample\Bots\DefaultActivityHandler.cs:line 44
at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in C:\Users\pavolum\source\repos\botframework-solutions\sdk\csharp\libraries\microsoft.bot.solutions\Middleware\EventDebuggerMiddleware.cs:line 60
at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken) in C:\Users\pavolum\source\repos\botframework-solutions\sdk\csharp\libraries\microsoft.bot.solutions\Middleware\SetLocaleMiddleware.cs:line 30
at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

[bug]

**Comment by vishwacsena** [comment]
@garypretty @tomlm @cleemullins I believe this has been resolved. Can we close?

**Comment by cleemullins** [comment]
Confirmed with @tomlm this is resolved
