### ISSUE TITLE
Bot Builder C# SDK Cannot access a disposed object. Object name: 'SslStream'.

### ISSUE THREAD

**Issue by surezg** [microsoft/botbuilder-dotnet#3907]
Hello All,
I am getting this error frequently while sending message from bot to the user. Following is the code snippet where I receive this error. I am using bot builder sdk version 4.4.3

`ConnectorClient.Conversations.SendToConversationAsync(activity);`

Error:
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Bot.Connector.Conversations.SendToConversationWithHttpMessagesAsync(String conversationId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.SendToConversationAsync(IConversations operations, String conversationId, Activity activity, CancellationToken cancellationToken)
>

**Comment by dmvtech** [comment]
hi @surezg 
What channel is this happening on? 
Does it happen on more than one channel? 
Are you able to test and reproduce this on a bot using a more recent version (4.8.0 for example)?

**Comment by surezg** [comment]
> hi @surezg
> What channel is this happening on?
> Does it happen on more than one channel?
> Are you able to test and reproduce this on a bot using a more recent version (4.8.0 for example)?

I am using 4.4.3. Didn't tested with 4.8.0. Even this is rare occurrence and unable reproduce in dev environment or even in production. Bu in production we have seen this 4 to 5 times in the past 3 weeks.

**Comment by dmvtech** [comment]
@Wajeed-msft Would you be able to help out on this to take a look from the Teams side of things? Ever seen this or similar issue happen before?
