### ISSUE TITLE
Teams and Skype do not return a ResourceResponse for typing activities

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/botbuilder-dotnet#465]
Reporting bug for issue #460. When using teams and skype, the channels do not return a `ResourceResponse` after an `ActivityType.Typing` has been sent.  

The code Blows up on this line [`var activity = activityList[i];`](https://github.com/Microsoft/botbuilder-dotnet/blob/8acf7a9e118863764b76abef83fb3575165e70dd/libraries/Microsoft.Bot.Builder.Core/TurnContext.cs#L255)  Because there is no response from the [`SendToConversationWithHttpMessagesAsync`](https://github.com/Microsoft/botbuilder-dotnet/blob/25ee60226abc4dcc048868711090302479315a8d/libraries/Microsoft.Bot.Connector/Conversations.cs#L471) method

Stack Trace:
```
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivities>g__ActuallySendStuff|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivitiesInternal>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivities>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivity>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNetCore_EchoBot_With_State.EchoBot.<OnTurn>d__0.MoveNext() in C:\source\gitHub\botbuilder-dotnet\AspNetCore-EchoBot-With-State\EchoBot.cs:line 32
```

**Comment by cleemullins** [comment]
Closed by #480
