### ISSUE TITLE
TextInput throwing when input is not in string format

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/botbuilder-dotnet#4948]
## Version
4.10.5

## Describe the bug
The TextInput dialog throws when the input in context.Activity.Text is empty and context.Activity.Value contains an object. This happens, for example, when the bot uses adaptive cards and it specifies an object as the value to be returned to the bot service. In this situation, the TextInput throws an exception like the following:

```
System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Bot.Builder.Dialogs.ObjectPath.MapValueTo[T](Object val)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at Microsoft.Bot.Builder.Dialogs.ObjectPath.TryGetPathValue[T](Object obj, String path, T& value)
   at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.TryGetValue[T](String path, T& value)
   at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.GetValue[T](String pathExpression, Func`1 defaultValue)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.TextInput.OnRecognizeInputAsync(DialogContext dc, CancellationToken cancellationToken)
```

## To Reproduce

Write an adaptive dialog like the one below, and run it in MS Teams:

```cs
// Send an adaptive card with an object as the value to be passed back to the bot
new SendActivity("${SubmitForm()}"),
// Send an text input
new TextInput()
{
    Property = "$textinput",
    Prompt = new ActivityTemplate("Please type something"),
    AlwaysPrompt = true
}
```

The content of the SubmitForm template can be as follows (using lg):

```
# SubmitForm
[Activity
    Attachments = ${json(SubmitFormMsg())}
]

# SubmitFormMsg()
- ```
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Here's a submit button"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit",
            "data": {
                "msteams": {
                    "type": "messageBack",
                    "displayText": "nothing much",
                    "text": "",
                    "value": {"InputSource": "MyCard"}
                }
            }
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```
Once the bot sends the adaptive card and waits for the user input, click on the submit button from the adaptive card. This should trigger the exception in the TextInput.

## Expected behavior
The text input should fail the input validation and reprompt the user for a valid input, instead of throwing an exception.

**Comment by johnataylor** [comment]
This fix should be in the next release 4.12 this is currently targeted for next Feb
