### ISSUE TITLE
Proactive messaging throws OAuthExcption (Unauthorized)

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#498]
## Setup
1. Create a bot and assign it credentials.
2. Add proactive call
    ```csharp
    public class ProactiveBot : IBot
    {
        public async Task OnTurn(ITurnContext context)
        {
            if (context.Activity.Type is ActivityTypes.Message)
            {
                var messageText = context.Activity.AsMessageActivity()?.Text;
                if (messageText?.Trim().ToLowerInvariant() is "subscribe")
                {
                    // Confirm the request.
                    await context.SendActivity("Thank You! We will message you shortly.");

                // Queue the proactive message.
                var reference = TurnContext.GetConversationReference(context.Activity);

                // This is working, but is a workaround.
                //SubscribeUser(context.Adapter as BotFrameworkAdapter, GetAppId(context), reference);

                // 4/23: This should work, but throws an authorization exception outside of the middleware pipeline.
                SubscribeUser(context.Adapter, reference);
                }
                else
                {
                    // Prompt the user to subscribe.
                    await context.SendActivity("Type `subscribe` to receive a proactive message.");
                }
            }
        }

        private static string GetAppId(ITurnContext context)
        {
            var claimsIdentity = context.Services.Get<IIdentity>("BotIdentity") as ClaimsIdentity;
            Contract.Requires(claimsIdentity != null);

            // For requests from channel App Id is in Audience claim of JWT token. For emulator it is in AppId claim. For 
            // unauthenticated requests we have anonymouse identity provided auth is disabled.
            // For Activities coming from Emulator AppId claim contains the Bot's AAD AppId.
            var botAppIdClaim =
                (claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AudienceClaim)
                ?? claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AppIdClaim));

            Contract.Ensures(botAppIdClaim != null);
            Contract.Ensures(botAppIdClaim.Value != null);

            return botAppIdClaim?.Value;
        }

        private async void SubscribeUser(BotAdapter adapter, ConversationReference reference)
        {
            // Send a proactive message.
            await adapter.ContinueConversation(reference.Bot.Id, reference, async context =>
            {
                await Task.Delay(2000);
                await context.SendActivity("You've been notified!");
            });
        }

        private async void SubscribeUser(BotFrameworkAdapter adapter, string appId, ConversationReference reference)
        {
            // Send a proactive message.
            await adapter.ContinueConversation(appId, reference, async context =>
            {
                await Task.Delay(2000);
                await context.SendActivity("You've been notified!");
            });
        }
    }
    ```
1. Run the bot locally.
1. Test it in the old emulator.

## Result
I see this against the bits I built this morning (4/23):
```test
Hosting environment: Development
Content root path: C:\Users\v-jofing\source\repos\ProactiveMessaging
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Unhandled Exception: Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials+OAuthException: Unauthorized ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<RefreshTokenAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<RefreshTokenAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<GetTokenAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<ProcessHttpRequestAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Adapters.BotFrameworkAdapter.<SendActivities>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivities>g__ActuallySendStuff|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.TurnContext.<SendActivitiesInternal>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.TurnContext.<SendActivities>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.TurnContext.<SendActivity>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.TurnContext.<SendActivity>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Samples.ProactiveBot.<OnException>d__2.MoveNext() in C:\Users\v-jofing\source\repos\ProactiveMessaging\ProactiveBot.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Core.Extensions.CatchExceptionMiddleware`1.<OnTurn>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatus>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotAdapter.<RunPipeline>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Adapters.BotFrameworkAdapter.<ContinueConversation>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Samples.ProactiveBot.<SubscribeUser>d__3.MoveNext() in C:\Users\v-jofing\source\repos\ProactiveMessaging\ProactiveBot.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by drub0y** [comment]
Err... sorry, your sample code doesn't actually seem like it could work because you're calling an overload of `SubscribeUser` that doesn't take the `appId` that your `SubscribeUser` method signature actually requires. Not only that, but you couldn't just pass `context.Adapter` like that because it's of type `BotAdapter` and your `SubscribeUser` needs a `BotFrameworkAdapter`. (Side note: [this is exactly what I mentioned today](https://github.com/Microsoft/botbuilder-dotnet/issues/466#issuecomment-383639629) in #466).

I just want to make sure we're understanding your exact scenario. If you could put the full repro code in a gist or separate git repo that would be awesome.

**Comment by JonathanFingold** [comment]
@drub0y , I've fixed my copy-paste error and have just included the full bot code. Agreed that this issue is very similar to #466, if not an outright duplicate.

**Comment by JonathanFingold** [comment]
@drub0y , the following overload works, passing in the value from my GetAppId(context) call:
```csharp
private async void SubscribeUser(BotAdapter adapter, string appId, ConversationReference reference)
{
    // Send a proactive message.
    await adapter.ContinueConversation(appId, reference, async context =>
    {
        await Task.Delay(2000);
        await context.SendActivity("You've been notified using the BotAdapter and the BotAppId!");
    });
}
```
However, this is probably dependent on the BotFrameworkAdapter setting the "BotIdentity" ClaimsIdenty behind the scenes.
