### ISSUE TITLE
Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by dinirichard** [microsoft/botbuilder-dotnet#5006]
### The error originates from the await ConversationState.SaveChangesAsync(turnContext, false, cancellationToken); inside the Startup.cs

`adapter.OnTurnError = async (turnContext, exception) =>
            {
                await turnContext.SendActivityAsync(exception.Message).ConfigureAwait(false);
                await conversationState.ClearStateAsync(turnContext).ConfigureAwait(false);
                await conversationState.SaveChangesAsync(turnContext).ConfigureAwait(false);
            };
            return adapter;`

## Version
Microsoft.Bot.Builder.ApplicationInsights Version="4.11.0"
Microsoft.Bot.Builder.AI.QnA Version="4.11.0"
Microsoft.Bot.Builder.Azure Version="4.11.0"
Microsoft.Bot.Builder.Dialogs Version="4.11.0"
Microsoft.Bot.Builder.Dialogs.Adaptive Version="4.11.0"
Microsoft.Bot.Builder.Dialogs.Debugging Version="4.11.0-preview"
Microsoft.Bot.Builder.Integration.ApplicationInsights.Core Version="4.11.0"
Microsoft.Bot.Builder.Integration.AspNet.Core Version="4.11.0"

## Describe the bug
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM4KCLQQK8KS", Request id "0HM4KCLQQK8KS:00000001": An unhandled exception was thrown by the application.
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions)
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.InitializeAsync()
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotState.SaveChangesAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken)
   at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.<>c__DisplayClass12_0.<<GetBotAdapter>b__0>d.MoveNext() in E:\Bots\QnAMakerLUIS-test\runtime\azurewebapp\Startup.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity claimsIdentity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync() in E:\Bots\QnAMakerLUIS-test\runtime\azurewebapp\Controllers\BotController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

## Screenshots
![image](https://user-images.githubusercontent.com/36500470/100543007-4fa93e80-3256-11eb-8628-83bdedffc25e.png)

![image](https://user-images.githubusercontent.com/36500470/100543054-972fca80-3256-11eb-937a-ae1896a5cfeb.png)

## Additional context
Windows 10

**Comment by v-kydela** [comment]
Thank you for the report, @dinirichard 

It looks like you're using Cosmos DB. Is that correct?

It seems that your Cosmos DB endpoint is not formatted correctly. Perhaps you forgot to include the `https://` at the beginning. Can you verify that your Cosmos DB endpoint is correct?

[Here](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=net-5.0#System_Uri__ctor_System_String_) you can see all the ways that `Uri` constructor can throw that exception.

**Comment by dinirichard** [comment]
Thanks a lot @v-kydela,

That was the exact solution.

**Comment by v-kydela** [comment]
Glad to hear it
