### ISSUE TITLE
Adaptive dialog prompts do not work for EnglishOther locales without messy workaround

### ISSUE THREAD

**Issue by scurvydoggo** [microsoft/botbuilder-dotnet#5075]
## Version
4.11.1

## Channel
Microsoft Teams

## Describe the bug
I am in Australia, so my locale defaults to `en-GB`.

With an adaptive dialog, I get a key-not-found error with the `ChoiceInput` dialog (also occurs with `ConfirmInput` I noticed).

It is because only `en-us` appears in this `DefaultChoiceOptions` dictionary:
https://github.com/microsoft/botbuilder-dotnet/blob/be61ebb6450b0277279f002fe16270f021ceee53/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs#L221

It would be good if the above code was a function, instead of a dictionary index, which was able to softly match `en-*`  to the `English` option. This would solve the issue for English locales, but not for other less common locales though.

Note: I am able to work around it by setting `ChoiceOptions`, however it is not ideal due to the boilerplate. Instead I ended up just forcing my locale globally to `en-us` since my app is limited to our region, and `en-us` is close enough for us.

## To Reproduce
1. Clone `BotBuilder-Samples`
2. `cd` into `adaptive-dialog/01.multi-turn-prompt`
3. `dotnet run`
4. Talk to the bot with MS teams (I did not encounter an error with the emulator)
5. On the choice input, an error will occur:
```
fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      [OnTurnError] unhandled error : The given key 'en-GB' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key 'en-GB' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.ConfirmInput.OnRenderPromptAsync(DialogContext dc, InputState state, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog.PromptUserAsync(DialogContext dc, InputState state, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
...
```

## Expected behavior
No errors occur

**Comment by gabog** [comment]
Hi @luhan2017, can you take a look at this one please?

Thanks

**Comment by zidaneymar** [comment]
Hi @scurvydoggo , I think you could set this [ChoiceOptions ](https://github.com/microsoft/botbuilder-dotnet/blob/be61ebb6450b0277279f002fe16270f021ceee53/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs#L110)to include your own locale en-GB, you should edit your ChoiceInput action and add a additional field named ChoiceOptions, and it's a dictionary which accepts en-GB as a key.

**Comment by srinaath** [comment]
Closing for inactivity.
