### ISSUE TITLE
Not able to parse DateTimeSpec value "the hour" while reading response from luis in bot app

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botbuilder-dotnet#5291]
Ask
=======
May I know why "the hour" text could not be converted in DateTimeSpec type? Do I need to tweak something from my c# model side to allow it?

Package
==========
```<PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.12.0" />```

Luis response JSON
==========================
```
{
  "useralias": [
    "abcd"
  ],
  "number": [
    2
  ],
  "datetime": [
    {
      "timex": [
        "(T14, T15,PT1H)"
      ],
      "type": "timerange"
    },
    "the hour"
  ],
  "personName": [
    "Tony"
  ],
  "$instance": {
    "useralias": [
      {
        "type": "useralias",
        "text": "abcd",
        "startIndex": 0,
        "endIndex": 10,
        "modelType": "Entity Extractor",
        "recognitionSources": [
          "model"
        ]
      }
    ],
    "number": [
      {
        "type": "builtin.number",
        "text": "2",
        "startIndex": 31,
        "endIndex": 32,
        "modelType": "Prebuilt Entity Extractor",
        "recognitionSources": [
          "model"
        ]
      }
    ],
    "datetime": [
      {
        "type": "builtin.datetimeV2.timerange",
        "text": "2 to 3pm",
        "startIndex": 31,
        "endIndex": 39,
        "modelType": "Prebuilt Entity Extractor",
        "recognitionSources": [
          "model"
        ]
      },
      {
        "type": "builtin.datetimeV2.duration",
        "text": "the hour",
        "startIndex": 99,
        "endIndex": 107,
        "modelType": "Prebuilt Entity Extractor",
        "recognitionSources": [
          "model"
        ]
      }
    ],
    "personName": [
      {
        "type": "builtin.personName",
        "text": "Tony",
        "startIndex": 59,
        "endIndex": 65,
        "modelType": "Prebuilt Entity Extractor",
        "recognitionSources": [
          "model"
        ]
      }
    ]
  }
}
```
Error
==========
```
{"Error converting value \"the hour\" to type 'Microsoft.Bot.Builder.AI.Luis.DateTimeSpec'. Path 'entities.datetime[1]', line 1, position 362."}

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Luis.GeneralLuis.Convert(Object result) 
   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.<RecognizeAsync>d__26`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OOFAssistant.Controllers.NotifyController.<PullAliasRecord>d__17.MoveNext() 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OOFAssistant.Controllers.NotifyController.<BotCallback>d__15.MoveNext() 
```
Inner exception
====================
```
Could not cast or convert from System.String to Microsoft.Bot.Builder.AI.Luis.DateTimeSpec.

   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```
Convert logic
===========================
```
        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<GeneralLuis>(
                JsonConvert.SerializeObject(
                    result,
                    new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Error = OnError }
                )
            );
```

**Comment by dmvtech** [comment]
Hi @PurnaChandraPanda I'm looking into this and will share my findings.

**Comment by carlosscastro** [comment]
@dmvtech any updates on this?

**Comment by dmvtech** [comment]
Hi @PurnaChandraPanda I'm not quite getting the same results as you. Can you tell me what the full utterance is that you are using?

**Comment by PurnaChandraPanda** [comment]
Hi @dmvtech 

Here is the utterance
```
jode - away 2 to 3pm >>> John is in an offline meeting between the hour. He is not available for issues in that time. Just FYI!
```

Thanks!

**Comment by dmvtech** [comment]
@PurnaChandraPanda 

So, there are two aspects to this. 

First of all, the utterance 'between the hour' doesn't really fit in a proper English vernacular. Something like 'between the hours of 2 to 3', 'an hour' or 'that hour' are.

Testing the following utterances using the [Timex sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/40.timex-resolution), I debugged to find the recognized results. 

### The following utterance (yours):
`"jode - away 2 to 3pm >>> John is in an offline meeting between the hour.";`

Gives two results. One for range, one for duration.
```
{Microsoft.Recognizers.Text.ModelResult}
    End: 19
    Resolution: Count = 1
    Start: 12
    Text: "2 to 3pm"
    TypeName: "datetimeV2.timerange"

{Microsoft.Recognizers.Text.ModelResult}
    End: 70
    Resolution: null
    Start: 63
    Text: "the hour"
    TypeName: "datetimeV2.duration"
```

Here we see that the duration has no resolution. Meaning **no values that are retrieved/extracted from that**. When running in the Timex example, this results in a null reference exception. I believe this is what is contributing to the LUIS/Serialization exception.

### The following utterance (mine):
`"jode - away 2 to 3pm >>> John is in an offline meeting for that hour.";`

Only gives a single recognizition (the range):
```
{Microsoft.Recognizers.Text.ModelResult}
    End: 19
    Resolution: Count = 1
    Start: 12
    Text: "2 to 3pm"
    TypeName: "datetimeV2.timerange"
```

### And finally, this utterance:
`"jode - away 2 to 3pm >>> John is in an offline meeting for an hour.";`

Gives two valid recognized, both duration and range. With the duration having resolution/values:
```
{Microsoft.Recognizers.Text.ModelResult}
    End: 23
    Resolution: Count = 1
    Start: 17
    Text: "an hour"
    TypeName: "datetimeV2.duration"
{Microsoft.Recognizers.Text.ModelResult}
    End: 37
    Resolution: Count = 1
    Start: 25
    Text: "from 2 to 3pm"
    TypeName: "datetimeV2.timerange"
```

So, I believe that this should/could be handled more gracefully in code. But be aware that that sample utterance you gave is not correct English and should be avoided if possible. 

I'll continue on this and let you know as I have more info.

**Comment by PurnaChandraPanda** [comment]
@dmvtech : I agree to your point. But, my users can file in such message. So, I would have to find a way to prepare for it.

On C# end, I have the luis option set to read as instance data.

```
                        luisOptions = new LuisRecognizerOptionsV3(luisApp)
                        {
                            TelemetryClient = telemetryClient,
                            LogPersonalInformation = true,
                            // added includeInstanceData property in prediction option
                            // to read the raw identified text as datetimev2 entity
                            PredictionOptions = new LuisV3.LuisPredictionOptions { 
                                IncludeInstanceData = true
                            }
                        };
```

Would things differ if reading datetimev2 results as instance data on client ent??

**Comment by peterinnesmsft** [comment]
@dmvtech is this issue with the SDK code or due to an error on the LUIS API side? That will help us determine where we need to route this issue. Thanks!

**Comment by dmvtech** [comment]
@peterinnesmsft I kinda see it as both.

When using the 'bad' phrase, LUIS/Timex does recognize two entities. One for duration and one for time range in the instance:

```
        "datetimeV2": [
          {
            "type": "builtin.datetimeV2.timerange",
            "text": "2 to 3pm",
            "startIndex": 12,
            "length": 8,
            "modelTypeId": 2,
            "modelType": "Prebuilt Entity Extractor",
            "recognitionSources": [
              "model"
            ]
          },
          {
            "type": "builtin.datetimeV2.duration",
            "text": "the hour",
            "startIndex": 63,
            "length": 8,
            "modelTypeId": 2,
            "modelType": "Prebuilt Entity Extractor",
            "recognitionSources": [
              "model"
            ]
```

But for entities, the duration is just the string `the hour` with no resolution:
```
      "datetimeV2": [
        {
          "type": "timerange",
          "values": [
            {
              "timex": "(T14,T15,PT1H)",
              "resolution": [
                {
                  "start": "14:00:00",
                  "end": "15:00:00"
                }
              ]
            }
          ]
        },
        "the hour"
      ],
```


But when using a more valid English phrase `an hour`, then we get:
```
      "datetimeV2": [
        {
          "type": "timerange",
          "values": [
            {
              "timex": "(T14,T15,PT1H)",
              "resolution": [
                {
                  "start": "14:00:00",
                  "end": "15:00:00"
                }
              ]
            }
          ]
        },
        {
          "type": "duration",
          "values": [
            {
              "timex": "PT1H",
              "resolution": [
                {
                  "value": "3600"
                }
              ]
            }
          ]
        }
      ],
```

So, I do see this as being a bug in LUIS (if it recognizes as a duration, it should be giving resolution as such. with timex and resolution value). I'll look into filing that. As i've tested with Timex classes, i'm not even sure if it's entirely a LUIS issue, as it pretty much starts with the datetime recognizers.

But I'm wonder if the [DateTimeSpec](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/DateTimeSpec.cs) class shouldn't' be changed to gracefully handle this (or another similar) scenario.

**Comment by dmvtech** [comment]
Still investigating on the LUIS side of things. Will update when have more details.

**Comment by dmvtech** [comment]
There is a bug in the text-recognizer which is leading to the issues predicting DateTimeV2. A fix is in the works. Updates as I have more information.

**Comment by dmvtech** [comment]
Fix is still in works for the recognizer. After that LUIS fixes will be implemented. I'll update as I hear more information.

**Comment by dmvtech** [comment]
Still waiting on fixes for Recognizers and LUIS.

**Comment by EricDahlvang** [comment]
Related: https://github.com/microsoft/botbuilder-dotnet/issues/5620

**Comment by cleemullins** [comment]
Note that due to the recognizers dropping .Net core version 2.0 compatibility, we cannot take the recognizers fix until next cycle when the SDK does the same. (.NEt Core 2.0 is no supported past that date). Pushing this to R15 so that once the dependencies are updated we can merge.

**Comment by ceciliaavila** [comment]
This issue is solved in the new version of Recognizers.
We are updating the .NET SDK to use these packages in PR #5992.
