### ISSUE TITLE
Telephony Channel: NullReferenceException with empty activity received by the bot

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/botbuilder-dotnet#5470]
## Version
4.11

## Describe the bug
An echo bot built with Composer 1.3.* and with Telephony Channel enabled drops messages every so often. App Insights shows that the bot fails the following the exception for the missing messages: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.Streaming.StreamingRequestHandler.ProcessRequestAsync(ReceiveRequest request, ILogger`1 logger, Object context, CancellationToken cancellationToken)

This happens for several different types of activities : conversationUpdate, messageactivity, eventActivity, commandActivity.

## To Reproduce
1. Create an echo bot using Composer 1.3 (enable app insights)
2. Enable the Telephony Channel
3. Call the bot repeatedly
4. Notice that ~1 in 6 calls has periods of silence (sometimes at the beginning of the call when greeting is lost, or bot does not echo back the message). 
5. App Insights shows the following exception: 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.Streaming.StreamingRequestHandler.ProcessRequestAsync(ReceiveRequest request, ILogger`1 logger, Object context, CancellationToken cancellationToken)

6. Further tracing shows the activity is sent by the channel and received by the Bot SDK --> streaming library. It is lost along the way from the Streaming library to the bot. 

## Expected behavior
Activities from the Telephony channel successfully reach the bot.

**Comment by carlosscastro** [comment]
Refactor of streaming lib ongoing will include a fix for this. ETA R14
