### ISSUE TITLE
GetConversationPagedMembersAsync call from skills returns NotImplemented error

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botbuilder-dotnet#5558]
## Version
What package version of the SDK are you using.
4.12.0

## Describe the bug
Give a clear and concise description of what the bug is.
We call GetConversationPagedMembersAsync to get teams channel members from the Skills. This calls the VA which returns Not implemented error.

It seems to be hitting the below code

https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceController.cs#L141
   https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder/ChannelServiceHandlerBase.cs#L423

## To Reproduce
Below is the snippet of the code we used.
private async Task<IEnumerable<ChannelAccount>> GetTeamMembershipAsync(
            IConversations conversations,
            string conversationId,
            CancellationToken cancellationToken)
        {
            var channelAccounts = new List<ChannelAccount>();

            string continuationToken = null;
            int pageCount = 0;
                PagedMembersResult pagedMemberResult = await conversations.GetConversationPagedMembersAsync(
                    conversationId,
                    MembershipPageSize,
                    continuationToken,
                    cancellationToken);

}
## Expected behavior
This should work and return the conversation members

## Additional context
Here is the stacktrace (truncated path)

  
   Operation returned an invalid status code 'NotImplemented'
      at Microsoft.Bot.Connector.Conversations.<GetConversationPagedMembersWithHttpMessagesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.<GetConversationPagedMembersAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Solutions.Channels.Teams.TeamsContext2.<GetTeamMembershipAsync>d__11.MoveNext() in C:\...\Channels\Teams\TeamsContext\TeamsContext.ChannelExtensions.cs:line 253
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Solutions.Channels.Teams.TeamsContext2.<GetTeamsMembershipAsync>d__5.MoveNext() in C:\...\Channels\Teams\TeamsContext\TeamsContext.ChannelExtensions.cs:line 78
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Icm.Extensions.Teams.TaskModule.Oncall.Engage.EngageContactTaskModuleHandler.<OnTeamsTaskModuleAsync>d__8.MoveNext() in C:\...\Extensions\Teams\TaskModule\Oncall\Engage\EngageContactTaskModuleHandler.cs:line 165
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Icm.Extensions.Teams.TaskModule.Oncall.Engage.EngageContactTaskModuleHandler.<OnTeamsTaskModuleFetchAsync>d__6.MoveNext() in C:\...\Extensions\Teams\TaskModule\Oncall\Engage\EngageContactTaskModuleHandler.cs:line 62
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Common.Teams.ActivityHandlers.TeamsInvokeActivityHandlerFactory.<GetTaskModuleFetch>d__5.MoveNext() in C:\...\ActivityHandlers\TeamsInvokeActivityHandlerFactory.cs:line 41
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Common.Teams.ActivityHandlers.TeamsInvokeActivityHandlerFactory.<HandleTaskModuleActivity>d__4.MoveNext() in C:\...\ActivityHandlers\TeamsInvokeActivityHandlerFactory.cs:line 27
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Icm.Bots.DefaultActivityHandler`1.<OnTeamsTaskModuleResponseAsync>d__14.MoveNext() in C:\...\Bots\DefaultActivityHandler.cs:line 75
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Teams.TeamsActivityHandler.<OnInvokeActivityAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.Skills.Icm.Bots.DefaultActivityHandler`1.<OnInvokeActivityAsync>d__17.MoveNext() in C:\...\Bots\DefaultActivityHandler.cs:line 108
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.ActivityHandler.<OnTurnAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Obi.Skills.Icm.Bots.DefaultActivityHandler`1.<OnTurnAsync>d__8.MoveNext() in C:\...\Bots\DefaultActivityHandler.cs:line 46

**Comment by GeoffCoxMSFT** [comment]
@mrivera-ms Could you assign to the right person to look into this?

**Comment by ipraveenMS** [comment]
This is resolved after I used https://smba.trafficmanager.net/amer for the service url
