### ISSUE TITLE
SetProperty throws in adaptive dialog for values starting with =

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/botbuilder-dotnet#5609]
## Version
4.13.2

## Describe the bug
The Bot Framework throws when calling SetProperty in an adaptive dialog and the value starts with `=`. The exception thrown looks like the one below:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.JsonExtensions.ReplaceJTokenRecursively(JToken token, Object state)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogManager.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in E:\repos\BotBuilder-Samples\samples\csharp_dotnetcore\adaptive-dialog\01.multi-turn-prompt\Bots\DialogBot.cs:line 33
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
```

## To Reproduce
1. Start from the [multi-turn prompt bot](https://github.com/microsoft/BotBuilder-Samples/tree/901bc140f5aa300fbfa852e64afd7c65fceebff9/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt) from botbuilder-samples;
2. Modify the root dialog to have something like this:

```
// Get the user input
new TextInput()
{
    Prompt = new ActivityTemplate("Type something"),
    Property = "$userInput"
},
// Set it to a property
new SetProperty
{
    Property = "$copyUserInput",
    Value = "=$userInput"
},
// Print it back
new SendActivity("${$copyUserInput}")
```

3. Run the bot, and type something that starts with a `=`:

![image](https://user-images.githubusercontent.com/14302074/119579664-bf1a6980-bd73-11eb-84a7-f21c6d0a20b9.png)

4. The bot will throw.

If, on step 3, you type anything else, the bot works as expected:

![image](https://user-images.githubusercontent.com/14302074/119580346-081eed80-bd75-11eb-9c75-9a7a7dbbac2f.png)

## Expected behavior
SetProperty should not throw depending on the user input.

**Comment by johnataylor** [comment]
The AdaptiveDialog stack relies on MemoryScopes. 4.13 introduced a change where these were no longer global variables. The impact of this fix was handled in the regular Adaptive Dialog execution (meaning starting from JSON in a ResourceProvider) however these "code-first" samples haven't been updated to address that.

As they are the samples depend on 4.12 and shouldn't have been updated to 4.13 but should remain on 4.12.

To be clear these code-first Adaptive Dialogs samples are provided as an illustration of how the underlying mechanisms work rather than as a recommended way to use the SDK. Writing Dialogs in code hasn't changed, the recommendation is to use Waterfall and Prompts.

Adaptive Dialogs are the runtime behind Composer and the classes are created by de-serializing JSON. The resulting class structure and the JSON are isomorphic. There is nothing to be gained by hand coding the class structure - that code is simply the construction of a data structure. The recommended route to using Adaptive Dialogs is to use Composer. Adaptive Dialogs and Dialogs written in code using Waterfall and Prompts interoperate seamlessly.

Having said that, it should be straight forward to set up the appropriate MemoryScopes in sample code. An illustration of what's required is actually in the implementation of the AdaptiveDialogBot. However, you can't use that code directly because it assumes the Adaptive Dialog was defined in JSON.

**Comment by fabio-muramatsu** [comment]
I think we had an extensive conversation about this story about using composer vs writing adaptive dialogs in code directly, so I won't go into it. Are you saying that the fact that the bot throws for a specific input can be explained by a missing memory scope? I should just add that this also repros in 4.12.

**Comment by johnataylor** [comment]
No you're right. I'm just debugging it right now

**Comment by johnataylor** [comment]
OK good to know. This is nothing to do with the change we did in 4.13. In fact when I run this sample as is it seems to be OK in 4.13. (It wouldn't be OK if it did more - it depends - that fragile nature of it was a big part of what we were fixing.)

**Comment by johnataylor** [comment]
does this happen if you generate the same logic but use composer?

**Comment by johnataylor** [comment]
OK so you say this is not a regression - you see this behavior in 4.12

 I can repro this using JSON so this is not special to code-first construction, here is my JSON version:
 
 ```
 {
  "$kind": "Microsoft.AdaptiveDialog",
  "triggers": [
    {
      "$kind": "Microsoft.OnUnknownIntent",
      "actions": [
        {
          "$kind": "Microsoft.TextInput",
          "prompt": "Type something",
          "property": "$userInput"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "property": "$copyUserInput",
          "value": "=$userInput"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "activity": "${$copyUserInput}"
        }
      ]
    }
  ]
}
``` 
 
As @fabio-muramatsu describes, given this flow you can get the following error, if you type in something that might be interpreted as an expression, for example, try typing "=abc" and you get an exception "Value cannot be null. (Parameter ‘o’)"

**Comment by johnataylor** [comment]
This looks like a bug @boydc2014 can you take a look? User entered data can be interpreted as executable expression. Note this exception might surface differently depending on how you set up the runtime. In my test code I simply used AddBotRuntime() directly in the startup.cs.

@fabio-muramatsu as you are constructing everything in code, you can try a workaround of the issue with custom code to filter the given input.

**Comment by boydc2014** [comment]
> This looks like a bug @boydc2014 can you take a look? User entered data can be interpreted as executable expression. Note this exception might surface differently depending on how you set up the runtime. In my test code I simply used AddBotRuntime() directly in the startup.cs.
> 
> @fabio-muramatsu as you are constructing everything in code, you can try a workaround of the issue with custom code to filter the given input.

Yes, @johnataylor. So after digging into it, besides the error message is confusing, this behavior is by design. The context is, per customer's feature request, in https://github.com/microsoft/botbuilder-dotnet/pull/4291/files, we make this SetProperty's "value" field a "deep data binding" field, which is basically saying, we will look into the evaluated result and keep trying to do data binding inside if we see a notion for databinding.  (the notion for data binding is either ${} or string begin with =)

In this case, value: "=${userInput}" is firstly evaluated to "=abc", then the deep binding mechanism works because of this = at beginning. So it will try to look up abc in the memory and find nothing, then exception is thrown. 

The issues we should solve are
1. The error message is not friendly, which we should at least get a better error message
2. This deep binding implementation probably convers more cases than it is supposed to be. We should scope down the deep data binding to the cases when the value is an object like value: { prop: "${abc}" }, which is the case user may expect a deep binding. We shouldn't do deep binding it when it's a just a plain string like value: "=$userinput".  This should fix the most cases

Also, the original deep binding method is doing this recursively, which might need a review see if it's necessary. Probably not a priority now.
