### ISSUE TITLE
Utterence cannot be null

### ISSUE THREAD

**Issue by mjwsteenbergen** [Microsoft/botbuilder-dotnet#572]
At [LuisRecognizer.cs#L58](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizer.cs#L58) there exists a line to check that the utterence is not null. However, when a user uploads a file (image,recording), there exists no such utterence. This results in an exception.

Tested in Telegram, Web Chat and Emulator

Full stacktrace:
```
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.RecognizeInternal(String utterance, CancellationToken ct)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.<Recognize>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizerMiddleware.<OnTurn>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Core.Extensions.CatchExceptionMiddleware`1.<OnTurn>d__2.MoveNext()
```

I implemented LUIS following the [bot framework tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)

**Comment by cleemullins** [comment]
Good Catch. 

@emadelwany, could you take a look and confirm the correct behavior?

**Comment by SHUBHAMARORA731** [comment]
I am facing the same issue using the latest package from NuGet . when can we expect the next release of the package including this resolution.

**Comment by FrancescoAntonelli** [comment]
Hi when is planned the merge of this issue?
Thanks
  Francesco
