### ISSUE TITLE
Unhandled 409 BlobAlreadyExists error when uploading activities to Azure Blob

### ISSUE THREAD

**Issue by rmt2021** [microsoft/botbuilder-dotnet#6350]
## Version
9ea8e1367e7b34cd84bfcf3ebae508599dfdc785

## Describe the bug
We encountered an `Azure.RequestFailedException : The specified blob already exists` when uploading the log activities via [`LogActivityAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/4cab8f1d039fef6101e2d7c6ca4deb454d4cbde0/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L107). The reason behind is that, in [`LogActivityToBlobClientAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/4cab8f1d039fef6101e2d7c6ca4deb454d4cbde0/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L411), Azure SDK API [`UploadAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/4cab8f1d039fef6101e2d7c6ca4deb454d4cbde0/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L440) is called to upload the log activities to the Azure blob storage, however, transient errors happened during the uploading, so the SDK's retry mechanism would send a new request to upload the data again though the first upload succeeded. More concretely:
1. Azure SDK API `UploadAsync` sent a request to upload the log activities;
2. The uploading succeeded in the cloud, and the server sent a success HTTP response back to the Botbuilder, however, the response did not arrive at the client on time due to transient network errors (e.g., timeout, package lost etc.). So the client did not recognize that the upload was completed;
3. The retry mechanism in Azure SDK would send the same request again to the server;
4. Since the activities had already been stored successfully in the remote, the retry request received `Azure.RequestFailedException : The specified blob already exists` 

## To Reproduce
As mentioned above, transient network errors may happen during the period when the upload finishes, but the response does not arrive the client, which will lead to the unhandled exception for `UploadAsync`.
<details>
<summary>stack trace</summary>

```
Azure.RequestFailedException : The specified blob already exists.RequestId:90e12d97-fb10-406a-a95a-eee21fc09586Time:2022-04-29T16:26:47.8563644Z
Status: 409 (The specified blob already exists.)
Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 90e12d97-fb10-406a-a95a-eee21fc09586
x-ms-version: 2020-04-08
x-ms-error-code: BlobAlreadyExists
Date: Fri, 29 Apr 2022 16:26:47 GMT
Connection: keep-alive
Content-Length: 220
Content-Type: application/xml

at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, String blobTagsString, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.  c__DisplayClass54_0.  GetPartitionedUploaderBehaviors b__0 d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.UploadAsync(Stream content, BlobUploadOptions options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Azure.Blobs.BlobsTranscriptStore.LogActivityToBlobClientAsync(IActivity activity, BlobClient blobClient, Boolean overwrite) in C:\Users\yinfang\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure.Blobs\BlobsTranscriptStore.cs:line 440
   at Microsoft.Bot.Builder.Azure.Blobs.BlobsTranscriptStore.LogActivityAsync(IActivity activity) in C:\Users\yinfang\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure.Blobs\BlobsTranscriptStore.cs:line 162
... 
```
</details>

### Expected Behavior & Possible fix
We think it is better to wrap the `UploadAsync` in a try-catch block to log down some messages when transient network errors happen. Besides, it is safer to check the existence of the blob before calling `UploadAsync`, so we can know it is due to transient errors when the 409 appears, and later the exception can be ignored. 

Another quick fix is to set the overwrite parameter of [`InnerLogActivityAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/4cab8f1d039fef6101e2d7c6ca4deb454d4cbde0/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L162) to true instead of false.

## Additional context
We are willing to submit a PR to fix it.

**Comment by LeeParrishMSFT** [comment]
@rmt2021 Thanks for filing this issue, and providing such a detailed analysis of the root cause. If you'd like to submit a PR for this we will be happy to evaluate it for addition in a future release.

**Comment by tdurnford** [comment]
@rmt2021 Closing due to inactivity. Please reopen once you create a PR.
