### ISSUE TITLE
Can you add a log line for this exception?

### ISSUE THREAD

**Issue by sandrock** [microsoft/botbuilder-dotnet#6577]
My bot does not work for an obscure authentication reason. I believe the runtime goes into [this line of code](https://github.com/microsoft/botbuilder-dotnet/blob/042ee483694a84410e9c7f5420a09b8dbe6a87d7/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs#L115). 

Can someone add a `logger.LogWarning` call with detailled info so I can know what is happening?  

```
catch (UnauthorizedAccessException)
{
    // handle unauthorized here as this layer creates the http response
    httpResponse.StatusCode = (int)HttpStatusCode.Unauthorized;
    // TODO: can you log info here?
}
```

My log file is like that:

> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://somewhere/api/messages application/json;+charset=utf-8 475
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'TeamsBot.Controllers.BotController.PostAsync (TeamsBot)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Bot"}. Executing controller action with signature System.Threading.Tasks.Task PostAsync() on controller TeamsBot.Controllers.BotController (TeamsBot).
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      ProcessActivityAsync
dbug: BotController[0]
      Adapter=TeamsBot.CloudAdapterWithErrorHandler Bot=TeamsBot.Bots.EchoBot ProcessAsync done. Microsoft.AspNetCore.Http.DefaultHttpRequest -> Microsoft.AspNetCore.Http.DefaultHttpResponse
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action TeamsBot.Controllers.BotController.PostAsync (TeamsBot) in 991.5981ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'TeamsBot.Controllers.BotController.PostAsync (TeamsBot)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://somewhere/api/messages application/json;+charset=utf-8 475 - 401 0 - 1078.8221ms

As you can see, the last line indicates my controller returns a HTTP 401 code. The controller action is calling `await this.adapter.ProcessAsync(this.Request, this.Response, this.bot);` (`this.adapter` is of type `IBotFrameworkHttpAdapter`, the instance of `this.adapter` is `CloudAdapterWithErrorHandler`, which inherits [`Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter`](https://github.com/microsoft/botbuilder-dotnet/blob/042ee483694a84410e9c7f5420a09b8dbe6a87d7/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs). 

---

Referencing BotBuilder 4.18.1.

Log config: 

```
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "EchoBot": "Trace",
      "BotController": "Debug",
      "Microsoft": "Information",
      "TeamsBot.Bots.EchoBot": "Trace",
      "Microsoft.Hosting.Lifetime": "Information",
      "BotFrameworkHttpAdapter": "Trace",
      "Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter": "Trace",
      "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker": "Warning",
      "Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor": "Warning"
    },
    "File":{
      "Path": "logs/teamsbot.DATE.log"
    }
  }
```

**Comment by sandrock** [comment]
Thanks for the patch. My new log is:

> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://somwhere/api/messages application/json;+charset=utf-8 1062
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'TeamsBot.Controllers.BotController.PostAsync (TeamsBot)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Bot"}. Executing controller action with signature System.Threading.Tasks.Task PostAsync() on controller TeamsBot.Controllers.BotController (TeamsBot).
info: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      ProcessActivityAsync

> fail: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
      System.UnauthorizedAccessException: Invalid AppId passed on token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
         at Microsoft.Bot.Connector.Authentication.ChannelValidation.AuthenticateChannelToken(String authHeader, ICredentialProvider credentials, HttpClient httpClient, String channelId, AuthenticationConfiguration authConfig)
         at Microsoft.Bot.Connector.Authentication.ChannelValidation.AuthenticateChannelToken(String authHeader, ICredentialProvider credentials, String serviceUrl, HttpClient httpClient, String channelId, AuthenticationConfiguration authConfig)
         at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.AuthenticateTokenAsync(String authHeader, ICredentialProvider credentials, IChannelProvider channelProvider, String channelId, AuthenticationConfiguration authConfig, String serviceUrl, HttpClient httpClient)
         at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.ValidateAuthHeader(String authHeader, ICredentialProvider credentials, IChannelProvider channelProvider, String channelId, AuthenticationConfiguration authConfig, String serviceUrl, HttpClient httpClient)
         at Microsoft.Bot.Connector.Authentication.JwtTokenValidation.AuthenticateRequest(IActivity activity, String authHeader, ICredentialProvider credentials, IChannelProvider provider, AuthenticationConfiguration authConfig, HttpClient httpClient)
         at Microsoft.Bot.Connector.Authentication.BuiltinBotFrameworkAuthentication.AuthenticateRequestAsync(Activity activity, String authHeader, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.CloudAdapterBase.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)

> dbug: BotController[0]
      Adapter=TeamsBot.CloudAdapterWithErrorHandler Bot=TeamsBot.Bots.EchoBot ProcessAsync done. Microsoft.AspNetCore.Http.DefaultHttpRequest -> Microsoft.AspNetCore.Http.DefaultHttpResponse
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action TeamsBot.Controllers.BotController.PostAsync (TeamsBot) in 1064.143ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'TeamsBot.Controllers.BotController.PostAsync (TeamsBot)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://somwhere/api/messages application/json;+charset=utf-8 1062 - 401 0 - 1074.1526ms

I can now investigate my problem.
