### ISSUE TITLE
custom question answering multiturn does not work with QnAMakerDialog

### ISSUE THREAD

**Issue by Yongchao7** [microsoft/botbuilder-dotnet#6599]
## Version
4.19.3

## Describe the bug
I got the error Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.Int64' when use multiturn with custom question answering.
The error is throw from function 'ResetOptions' in
botbuilder-dotnet/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs

It will always throw the error because the dc.Context.Activity.Value of custom question answering is an object,  but resetOptions needs to convert it to an int. Should this convert be handled differently.

**Comment by anishprasad01** [comment]
Hi @Yongchao7,

In your `Startup.cs` file, try adding the following line in the `ConfugureServices` method:

```csharp
ComponentRegistration.Add(new DialogsComponentRegistration());
```

When I added this line to the [48.CustomQABot-all-features sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/48.customQABot-all-features), follow-up prompts and multiturn conversations worked correctly.

When you add that line of code, your IDE may warn you that the method is marked as obsolete. As per comment from the team [here](https://github.com/microsoft/BotBuilder-Samples/issues/3834), this is still the accepted implementation and there are no plans to drop or change it.

**Comment by ronikurnia1** [comment]
Hi @anishprasad01,

I've implemented your suggestion and it works on Emulator, TestInWebChat but not on MS Teams channel. 


> 
> In your `Startup.cs` file, try adding the following line in the `ConfigureServices` method:
> 
> ```cs
> ComponentRegistration.Add(new DialogsComponentRegistration());
> ```
> 
> When I added this line to the [48.CustomQABot-all-features sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/48.customQABot-all-features?rgh-link-date=2023-03-10T17%3A26%3A01Z), follow-up prompts and multiturn conversations worked correctly.
> 
> When you add that line of code, your IDE may warn you that the method is marked as obsolete. As per comment from the team [here](https://github.com/microsoft/BotBuilder-Samples/issues/3834), this is still the accepted implementation and there are no plans to drop or change it.

I got the same error message:

```shell
2023-03-14T03:12:38.220014423Z fail: Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter[0]
2023-03-14T03:12:38.220081225Z       [OnTurnError] unhandled error : Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.Int64'.
2023-03-14T03:12:38.220995559Z       System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.Int64'.
2023-03-14T03:12:38.221012060Z          at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.ResetOptions(DialogContext dc, QnAMakerDialogOptions dialogOptions)
2023-03-14T03:12:38.221017760Z          at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.OnPreBubbleEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
2023-03-14T03:12:38.221021660Z          at Microsoft.Bot.Builder.Dialogs.Dialog.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
2023-03-14T03:12:38.222232204Z          at Microsoft.Bot.Builder.Dialogs.DialogContext.EmitEventAsync(String name, Object value, Boolean bubble, Boolean fromLeaf, CancellationToken cancellationToken)
2023-03-14T03:12:38.222248805Z          at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
2023-03-14T03:12:38.222265206Z          at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
2023-03-14T03:12:38.222332708Z          at CustomQABot.Bots.CustomQABot`1.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in C:\Demos\QuestionAsweringBot\CustomQABotAllFeatures\Bots\CustomQABot.cs:line 64
2023-03-14T03:12:38.222347909Z          at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
2023-03-14T03:12:38.222352809Z          at CustomQABot.Bots.CustomQABot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Demos\QuestionAsweringBot\CustomQABotAllFeatures\Bots\CustomQABot.cs:line 44
2023-03-14T03:12:38.222356709Z          at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
2023-03-14T03:12:38.222360309Z          at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
```

**Comment by ronikurnia1** [comment]
Hi,

I think found the issue. It seems due to the type of **QnAId** (in Microsoft.Bot.Builder.AI.QnA project) are int (int64) while in multiturn scenario the value from MS teams something like this **"f:024f2e57-2b01-d703-0d97-008da7c94fa5"** which cannot be converted to int (int64).

Not sure if need to change the **QnAId** to string OR instead convert the value from MS Teams (f:024f2e57-2b01-d703-0d97-008da7c94fa5) into some int (int64).

**Comment by anishprasad01** [comment]
@ronikurnia1,

Thank you for this. If you would like to submit a PR, you're more than welcome to. Otherwise, as time allows, I will do it myself.

**Comment by anishprasad01** [comment]
@ronikurnia1,

Thank you very much for providing these details. I apologize, I did not realize this issue was specific to Teams.

I can create a PR and run the tests so that we can get this thing merged quickly.

**Comment by anishprasad01** [comment]
Fix will be available in the next patch release. No ETA at this time.
