### ISSUE TITLE
BotFrameworkHttpAdapter - Error Message: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KannanNaicker** [microsoft/botbuilder-dotnet#6653]
### ItemGroup
![image](https://github.com/microsoft/botbuilder-dotnet/assets/137806741/d6968c14-8c4b-4201-a092-5f44ef618324)

## Version
Bot Builder V4 SDK Template for Visual Studio EchoBot v4.5.0
<TargetFramework>netcoreapp2.1</TargetFramework>

## Describe the bug
Error in: BotFrameworkHttpAdapter - Error Message: Object reference not set to an instance of an object.

Stack Trace: at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)

at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)

at Chatbot.Bots.DialogBot1.OnMessageActivityAsync(ITurnContext1 turnContext, CancellationToken cancellationToken) in D:\a\1\s\Bots\DialogBot.cs:line 50

at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)

at Chatbot.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\a\1\s\Bots\DialogBot.cs:line 55

at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

Source: Microsoft.Bot.Builder.Dialogs

## Screenshots
![image](https://github.com/microsoft/botbuilder-dotnet/assets/137806741/a4f6496a-f64a-4762-93ca-d4be29df955c)

## Dialog Code
 protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            await _dialog.RunAsync(turnContext,_conversationState.CreateProperty<DialogState>("DialogState"),cancellationToken);
        }

**Comment by dmvtech** [comment]
Hi @KannanNaicker 

Can you try updating from .Net Core 2.1 to .NET 6?

Should be this line in the .csproj file:
```xml
<TargetFramework>net6.0</TargetFramework>
```

**Comment by KannanNaicker** [comment]
Hi Team,

Any updates on the duplicate error.
Could you help us to fix this issue asap.

Thanks,
Kannan Naicker

**Comment by dmvtech** [comment]
Can you try a clean or a rebuild of the project? If that doesn't work, can you try closing the solution in VS and then deleting the contents of the `bin` and `obj` folders and then retrying again in VS?
