### ISSUE TITLE
Luis middleware exception

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/botbuilder-dotnet#691]
I'm using `LuisRecognizerMiddleware` and when I try to upload an image in the emulator, it throws an exception:

```
Value cannot be null. Parameter name: utterance

   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.RecognizeInternal(String utterance, CancellationToken ct)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.<Recognize>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizerMiddleware.<OnTurn>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

If I disable the Luis middleware, then I've got the correct activity in the OnTurn handler. How should I configure Luis middleware to "un-handle" non text activities?

**Comment by cleemullins** [comment]
Today we removed the LUIS Middleware as part of some code cleanup. The Middleware was from a time when we though Middleware was the solution to everything and recent hacks showed that having this as Middleware led to confusion and incorrect code.
