### ISSUE TITLE
Convo state as Dictionary<string,object> + Azure Table Bot State = Error

### ISSUE THREAD

**Issue by leeroy79** [Microsoft/botbuilder-dotnet#898]
This doesn't happen when using memory-based state.

To reproduce :

1. Open sample project **AspNetCore-SinglePrompt-Bot**.
2. Change it to use Azure Table bot state.
![image](https://user-images.githubusercontent.com/3583901/44827181-9b6a7900-ac44-11e8-92a4-4c1ce438453b.png)
3. Add the **Microsoft.Bot.Builder.Azure** NuGet package.
4. Run the bot and connect in the emulator.
5. Two errors are received as soon as the emulator connects, seemingly involved with (de)serializing the state : 

System.Reflection.TargetParameterCountException: Parameter count mismatch.
at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.<>c__DisplayClass5_0.<Flatten>b__1(PropertyInfo propertyInfo) in C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\Common\\Table\\EntityPropertyConverter.cs:line 194\r\n   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.Flatten(Dictionary`2 propertyDictionary, Object current, String objectPath, HashSet`1 antecedents, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext) in C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\Common\\Table\\EntityPropertyConverter.cs:line 184\r\n   at Microsoft.WindowsAzure.Storage.Table.EntityPropertyConverter.Flatten(Object root, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext) in C:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\Common\\Table\\EntityPropertyConverter.cs:line 75\r\n   at Microsoft.Bot.Builder.Azure.AzureTableStorage.ToTableEntity(String key, Object value)\r\n   at Microsoft.Bot.Builder.Azure.AzureTableStorage.<>c.<Write>b__7_0(KeyValuePair`2 kv)\r\n   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
at Microsoft.Bot.Builder.Azure.AzureTableStorage.<Write>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Core.Extensions.BotState`1.<Write>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Core.Extensions.BotState`1.<WriteFromContextService>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Builder.Core.Extensions.BotState`1.<OnTurn>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Core.Extensions.CatchExceptionMiddleware`1.<OnTurn>d__2.MoveNext()

**Comment by sgellock** [comment]
Per @drub0y feedback, we've removed support for Table Storage.  Please consider CosmosDB, Blob

**Comment by doguva-msft** [comment]
Latest version of ObjectFlattenerRecomposer nuget package (baseline for the EntityPropertyConverter in SDK) supports this.
https://www.nuget.org/packages/ObjectFlattenerRecomposer/
