### ISSUE TITLE
System.ArgumentNullException on LuisRecognizer.RecognizeAsync

### ISSUE THREAD

**Issue by magencio** [Microsoft/botbuilder-dotnet#992]
## Version
Microsoft.Bot.Builder.AI.Luis v4.0.7

## Describe the bug
LuisRecognizer raises System.ArgumentNullException on a call to RecognizeAsync when LUIS returns something like the following:
"
{
  "query": "4",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.8575135
  },
  "entities": [
    {
      "entity": "4",
      "type": "builtin.datetime.time",
      "startIndex": 0,
      "endIndex": 0,
      "resolution": {
        "comment": "ampm",
        "time": "T04"
      }
    }
  ]
}
"

Exception details:
"
TraktBot.MyBot:Error: Exception caught : System.ArgumentNullException: Value cannot be null.
Parameter name: o
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JArray.FromObject(Object o, JsonSerializer jsonSerializer)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.ExtractEntityValue(EntityModel entity) in D:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 191
   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.ExtractEntitiesAndMetadata(IList`1 entities, IList`1 compositeEntities, Boolean verbose) in D:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 111
   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.<RecognizeInternalAsync>d__21.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.<RecognizeAsync>d__8.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder.AI.LUIS\LuisRecognizer.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TraktBot.MyBot.<IsTurnInterruptedAsync>d__7.MoveNext() in C:\_Git\TraktBotCSharp_v4\TraktBot\TraktBot\MyBot.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TraktBot.MyBot.<OnTurnAsync>d__6.MoveNext() in C:\_Git\TraktBotCSharp_v4\TraktBot\TraktBot\MyBot.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167
"

Issue only happens if LUIS results contain a builtin.datetime.time entity like the one above.

## Expected behavior
RecognizeAsync shouldn't fail with an exception.

## Additional context
I'm developing my bot with C# and .NET Core.

[bug]

**Comment by johnataylor** [comment]
@magencio 
how did you get a builtin.datetime.time?

In my test model I can only create a buildin.datetimeV2.time for example:
```
{
  "query": "at 4",
  "topScoringIntent": {
    "intent": "booking",
    "score": 0.95221436
  },
  "entities": [
    {
      "entity": "4",
      "type": "builtin.datetimeV2.time",
      "startIndex": 3,
      "endIndex": 3,
      "resolution": {
        "values": [
          {
            "timex": "T04",
            "type": "time",
            "value": "04:00:00"
          },
          {
            "timex": "T16",
            "type": "time",
            "value": "16:00:00"
          }
        ]
      }
    }
  ]
}
```

having said that I can make the LuisRecognizer not throw the null, that's easy, and its a good fix to be more defensive about the data coming off the network. However, my concern is that it won't actually return you the data you want.

**Comment by johnataylor** [comment]
I found out this is the old datetime resolution, in fact, this is deprecated in some locals (which is why I was struggling in getting repro) anyhow should be a simple fix. The recognizer will essentially pass through the JTokens with minimal interference.

**Comment by johnataylor** [comment]
Checked into master. This should be fixed in the next release.
